// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgxakGxoskTnx8PTrWc1Ylq--g3nMaG4w',
    appId: '1:287841445177:web:afaf8bf4047bec4cb4b4e8',
    messagingSenderId: '287841445177',
    projectId: 'vb216y6zl5b5b5yrmy6qpaylmmpgjf',
    authDomain: 'vb216y6zl5b5b5yrmy6qpaylmmpgjf.firebaseapp.com',
    storageBucket: 'vb216y6zl5b5b5yrmy6qpaylmmpgjf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBB68Sc0sxyp8VrdjHwaHc5lmFuV12-Nk',
    appId: '1:287841445177:android:99ad165eceb84d59b4b4e8',
    messagingSenderId: '287841445177',
    projectId: 'vb216y6zl5b5b5yrmy6qpaylmmpgjf',
    storageBucket: 'vb216y6zl5b5b5yrmy6qpaylmmpgjf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVdwLS4YyD8nEc4thdAUyFvfb1toa0jJA',
    appId: '1:287841445177:ios:801e271e1f6f5e51b4b4e8',
    messagingSenderId: '287841445177',
    projectId: 'vb216y6zl5b5b5yrmy6qpaylmmpgjf',
    storageBucket: 'vb216y6zl5b5b5yrmy6qpaylmmpgjf.firebasestorage.app',
    iosClientId: '287841445177-b2rn8qu9akskqff1982kes0eu2rh0a4e.apps.googleusercontent.com',
    iosBundleId: 'com.sajda.ap',
  );

}