class AllahName {
  final int number;
  final String arabic;
  final String transliteration;
  final String french;
  final String meaning;
  final String description;
  final String reflection;
  final List<String> attributes;

  AllahName({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.french,
    required this.meaning,
    required this.description,
    required this.reflection,
    required this.attributes,
  });

  static List<AllahName> getAllNames() {
    return [
      AllahName(
        number: 1,
        arabic: 'الرَّحْمَنُ',
        transliteration: 'Ar-Rahman',
        french: 'Le Tout Miséricordieux',
        meaning: 'Celui qui fait miséricorde à toute la création',
        description: 'Ce nom désigne la miséricorde universelle d\'Allah qui s\'étend à tous les êtres vivants, croyants et non-croyants.',
        reflection: 'Méditer sur ce nom nous rappelle que la miséricorde d\'Allah englobe toute chose et nous inspire à être miséricordieux envers autrui.',
        attributes: ['Miséricorde', 'Compassion', 'Bienveillance'],
      ),
      AllahName(
        number: 2,
        arabic: 'الرَّحِيمُ',
        transliteration: 'Ar-Rahim',
        french: 'Le Très Miséricordieux',
        meaning: 'Celui qui accorde Sa miséricorde spéciale aux croyants',
        description: 'Cette miséricorde est particulière et réservée aux croyants dans l\'au-delà.',
        reflection: 'Ce nom nous encourage à chercher la proximité d\'Allah pour bénéficier de Sa miséricorde spéciale.',
        attributes: ['Miséricorde spéciale', 'Récompense', 'Paradis'],
      ),
      AllahName(
        number: 3,
        arabic: 'المَلِكُ',
        transliteration: 'Al-Malik',
        french: 'Le Roi',
        meaning: 'Le Souverain absolu de l\'univers',
        description: 'Allah est le Roi suprême qui possède et gouverne tout ce qui existe.',
        reflection: 'Reconnaître Allah comme notre Roi nous aide à accepter Sa volonté et à Lui obéir.',
        attributes: ['Souveraineté', 'Autorité', 'Pouvoir'],
      ),
      AllahName(
        number: 4,
        arabic: 'القُدُّوسُ',
        transliteration: 'Al-Quddus',
        french: 'Le Pur',
        meaning: 'Celui qui est exempt de tout défaut',
        description: 'Allah est parfaitement pur, exempt de tout défaut et imperfection.',
        reflection: 'Ce nom nous inspire à purifier nos cœurs et nos actions de tout ce qui déplaît à Allah.',
        attributes: ['Pureté', 'Perfection', 'Sainteté'],
      ),
      AllahName(
        number: 5,
        arabic: 'السَّلاَمُ',
        transliteration: 'As-Salam',
        french: 'La Paix',
        meaning: 'Celui qui est source de paix et de sécurité',
        description: 'Allah est celui qui apporte la paix et protège de tout mal.',
        reflection: 'Invoquer ce nom apporte la sérénité et nous rappelle qu\'Allah est notre refuge.',
        attributes: ['Paix', 'Sécurité', 'Sérénité'],
      ),
      AllahName(
        number: 6,
        arabic: 'المُؤْمِنُ',
        transliteration: 'Al-Mu\'min',
        french: 'Le Fidèle',
        meaning: 'Celui qui accorde la sécurité et la foi',
        description: 'Allah est celui qui protège et accorde la foi à Ses serviteurs.',
        reflection: 'Ce nom renforce notre confiance en Allah et nous rappelle qu\'Il protège les croyants.',
        attributes: ['Fidélité', 'Protection', 'Foi'],
      ),
      AllahName(
        number: 7,
        arabic: 'المُهَيْمِنُ',
        transliteration: 'Al-Muhaymin',
        french: 'Le Dominateur',
        meaning: 'Celui qui veille sur toute chose',
        description: 'Allah surveille et contrôle tout ce qui existe dans l\'univers.',
        reflection: 'Savoir qu\'Allah veille sur nous nous rassure et nous encourage à bien agir.',
        attributes: ['Surveillance', 'Contrôle', 'Omnipresence'],
      ),
      AllahName(
        number: 8,
        arabic: 'العَزِيزُ',
        transliteration: 'Al-Aziz',
        french: 'Le Puissant',
        meaning: 'Celui qui est invincible et honoré',
        description: 'Allah possède une puissance absolue et est digne de tout honneur.',
        reflection: 'Ce nom nous rappelle qu\'Allah peut tout accomplir et qu\'Il mérite notre respect.',
        attributes: ['Puissance', 'Honneur', 'Invincibilité'],
      ),
      AllahName(
        number: 9,
        arabic: 'الجَبَّارُ',
        transliteration: 'Al-Jabbar',
        french: 'Le Contraignant',
        meaning: 'Celui qui répare et contraint',
        description: 'Allah répare ce qui est brisé et contraint les rebelles.',
        reflection: 'Ce nom nous montre qu\'Allah peut guérir nos blessures spirituelles.',
        attributes: ['Réparation', 'Justice', 'Contrainte'],
      ),
      AllahName(
        number: 10,
        arabic: 'المُتَكَبِّرُ',
        transliteration: 'Al-Mutakabbir',
        french: 'L\'Orgueilleux',
        meaning: 'Celui qui a le droit à l\'orgueil',
        description: 'Seul Allah a le droit d\'être orgueilleux car Il est parfait.',
        reflection: 'Ce nom nous enseigne l\'humilité et nous rappelle notre position devant Allah.',
        attributes: ['Grandeur', 'Suprématie', 'Majesté'],
      ),
      AllahName(
        number: 11,
        arabic: 'الخَالِقُ',
        transliteration: 'Al-Khaliq',
        french: 'Le Créateur',
        meaning: 'Celui qui crée à partir du néant',
        description: 'Allah est le créateur de tout ce qui existe.',
        reflection: 'Méditer sur la création nous rapproche d\'Allah et renforce notre foi.',
        attributes: ['Création', 'Innovation', 'Existence'],
      ),
      AllahName(
        number: 12,
        arabic: 'البَارِئُ',
        transliteration: 'Al-Bari\'',
        french: 'Le Créateur parfait',
        meaning: 'Celui qui crée avec perfection',
        description: 'Allah façonne Sa création avec une perfection absolue.',
        reflection: 'Contempler la perfection de la création nous émerveille devant la grandeur d\'Allah.',
        attributes: ['Perfection', 'Façonnage', 'Excellence'],
      ),
      AllahName(
        number: 13,
        arabic: 'المُصَوِّرُ',
        transliteration: 'Al-Musawwir',
        french: 'Le Formateur',
        meaning: 'Celui qui donne forme à Sa création',
        description: 'Allah donne à chaque créature sa forme unique et particulière.',
        reflection: 'Ce nom nous rappelle que chacun de nous est façonné de manière unique par Allah.',
        attributes: ['Formation', 'Unicité', 'Beauté'],
      ),
      AllahName(
        number: 14,
        arabic: 'الغَفَّارُ',
        transliteration: 'Al-Ghaffar',
        french: 'Le Pardonneur',
        meaning: 'Celui qui pardonne constamment',
        description: 'Allah pardonne sans cesse les péchés de Ses serviteurs repentants.',
        reflection: 'Ce nom nous encourage au repentir et nous donne espoir en la miséricorde divine.',
        attributes: ['Pardon', 'Repentir', 'Espoir'],
      ),
      AllahName(
        number: 15,
        arabic: 'القَهَّارُ',
        transliteration: 'Al-Qahhar',
        french: 'Le Dominateur suprême',
        meaning: 'Celui qui domine toute chose',
        description: 'Allah domine et contrôle absolument tout dans l\'univers.',
        reflection: 'Ce nom nous rappelle notre petitesse face à la grandeur d\'Allah.',
        attributes: ['Domination', 'Contrôle absolu', 'Suprématie'],
      ),
      AllahName(
        number: 16,
        arabic: 'الوَهَّابُ',
        transliteration: 'Al-Wahhab',
        french: 'Le Donateur',
        meaning: 'Celui qui donne généreusement',
        description: 'Allah accorde Ses bienfaits généreusement sans compter.',
        reflection: 'Ce nom nous inspire à être généreux et reconnaissants pour tous les dons d\'Allah.',
        attributes: ['Générosité', 'Dons', 'Bienfaisance'],
      ),
      AllahName(
        number: 17,
        arabic: 'الرَّزَّاقُ',
        transliteration: 'Ar-Razzaq',
        french: 'Le Pourvoyeur',
        meaning: 'Celui qui pourvoit à tous les besoins',
        description: 'Allah subvient aux besoins de toutes Ses créatures.',
        reflection: 'Ce nom renforce notre confiance qu\'Allah pourvoira toujours à nos besoins.',
        attributes: ['Subsistance', 'Provision', 'Abondance'],
      ),
      AllahName(
        number: 18,
        arabic: 'الفَتَّاحُ',
        transliteration: 'Al-Fattah',
        french: 'Celui qui ouvre',
        meaning: 'Celui qui ouvre les portes de la réussite',
        description: 'Allah ouvre les portes fermées et facilite les affaires difficiles.',
        reflection: 'Invoquer ce nom dans nos difficultés nous aide à trouver des solutions.',
        attributes: ['Ouverture', 'Facilitation', 'Solutions'],
      ),
      AllahName(
        number: 19,
        arabic: 'العَلِيمُ',
        transliteration: 'Al-Alim',
        french: 'L\'Omniscient',
        meaning: 'Celui qui sait tout',
        description: 'Allah connaît tout : le passé, le présent, le futur, l\'apparent et le caché.',
        reflection: 'Savoir qu\'Allah connaît tout nous incite à la sincérité dans nos actions.',
        attributes: ['Omniscience', 'Connaissance', 'Sagesse'],
      ),
      AllahName(
        number: 20,
        arabic: 'القَابِضُ',
        transliteration: 'Al-Qabid',
        french: 'Celui qui resserre',
        meaning: 'Celui qui restreint la subsistance',
        description: 'Allah peut restreindre Ses bienfaits par sagesse.',
        reflection: 'Les épreuves sont parfois des bénédictions déguisées pour notre croissance spirituelle.',
        attributes: ['Restriction', 'Sagesse divine', 'Épreuve'],
      ),
      AllahName(
        number: 21,
        arabic: 'البَاسِطُ',
        transliteration: 'Al-Basit',
        french: 'Celui qui élargit',
        meaning: 'Celui qui étend Ses bienfaits',
        description: 'Allah élargit Ses bienfaits à qui Il veut selon Sa sagesse.',
        reflection: 'Ce nom nous rappelle d\'être reconnaissants dans l\'abondance et patients dans la difficulté.',
        attributes: ['Extension', 'Abondance', 'Bienfaits'],
      ),
      AllahName(
        number: 22,
        arabic: 'الخَافِضُ',
        transliteration: 'Al-Khafid',
        french: 'Celui qui abaisse',
        meaning: 'Celui qui humilie les arrogants',
        description: 'Allah abaisse ceux qui s\'enorgueillissent et désobéissent.',
        reflection: 'Ce nom nous enseigne l\'humilité et nous met en garde contre l\'orgueil.',
        attributes: ['Humiliation', 'Justice', 'Leçon'],
      ),
      AllahName(
        number: 23,
        arabic: 'الرَّافِعُ',
        transliteration: 'Ar-Rafi',
        french: 'Celui qui élève',
        meaning: 'Celui qui élève en rang',
        description: 'Allah élève le rang de Ses serviteurs pieux et sincères.',
        reflection: 'Ce nom nous encourage à chercher l\'élévation spirituelle par les bonnes actions.',
        attributes: ['Élévation', 'Honneur', 'Récompense'],
      ),
      AllahName(
        number: 24,
        arabic: 'المُعِزُّ',
        transliteration: 'Al-Mu\'izz',
        french: 'Celui qui donne la puissance',
        meaning: 'Celui qui accorde l\'honneur',
        description: 'Allah accorde la puissance et l\'honneur à qui Il veut.',
        reflection: 'La vraie puissance vient d\'Allah, pas de nos propres efforts.',
        attributes: ['Puissance', 'Honneur', 'Dignité'],
      ),
      AllahName(
        number: 25,
        arabic: 'المُذِلُّ',
        transliteration: 'Al-Mudhill',
        french: 'Celui qui avilit',
        meaning: 'Celui qui humilie les injustes',
        description: 'Allah humilie ceux qui opprime et font du mal.',
        reflection: 'Ce nom nous rappelle que la justice divine finira toujours par triompher.',
        attributes: ['Humiliation', 'Justice', 'Châtiment'],
      ),
      // Ajout des 74 autres noms avec des descriptions complètes...
      AllahName(
        number: 26,
        arabic: 'السَّمِيعُ',
        transliteration: 'As-Sami',
        french: 'L\'Audient',
        meaning: 'Celui qui entend tout',
        description: 'Allah entend toutes les paroles, même les plus secrètes.',
        reflection: 'Savoir qu\'Allah entend nos invocations nous encourage à L\'invoquer constamment.',
        attributes: ['Audition', 'Écoute', 'Réponse'],
      ),
      AllahName(
        number: 27,
        arabic: 'البَصِيرُ',
        transliteration: 'Al-Basir',
        french: 'Le Clairvoyant',
        meaning: 'Celui qui voit tout',
        description: 'Allah voit tout, l\'apparent comme le caché.',
        reflection: 'Ce nom nous rappelle qu\'Allah voit nos actions et nos intentions.',
        attributes: ['Vision', 'Omnivoyance', 'Surveillance'],
      ),
      AllahName(
        number: 28,
        arabic: 'الحَكَمُ',
        transliteration: 'Al-Hakam',
        french: 'Le Juge',
        meaning: 'Celui qui tranche avec justice',
        description: 'Allah est le juge suprême qui tranche entre Ses créatures.',
        reflection: 'Ce nom nous rappelle le Jour du Jugement et nous incite à bien agir.',
        attributes: ['Jugement', 'Justice', 'Verdict'],
      ),
      AllahName(
        number: 29,
        arabic: 'العَدْلُ',
        transliteration: 'Al-Adl',
        french: 'Le Juste',
        meaning: 'Celui qui est parfaitement équitable',
        description: 'Allah ne commet aucune injustice, même infime.',
        reflection: 'Ce nom nous inspire à être justes dans nos relations avec autrui.',
        attributes: ['Justice', 'Équité', 'Droiture'],
      ),
      AllahName(
        number: 30,
        arabic: 'اللَّطِيفُ',
        transliteration: 'Al-Latif',
        french: 'Le Bienveillant',
        meaning: 'Celui qui est doux et subtil',
        description: 'Allah traite Ses créatures avec douceur et bienveillance.',
        reflection: 'Ce nom nous inspire à être doux et bienveillants envers les autres.',
        attributes: ['Douceur', 'Subtilité', 'Bienveillance'],
      ),
      
      // Noms 31-50
      AllahName(
        number: 31,
        arabic: 'الخَبِيرُ',
        transliteration: 'Al-Khabir',
        french: 'L\'Expert',
        meaning: 'Celui qui connaît les détails de toute chose',
        description: 'Allah connaît parfaitement les secrets et les détails les plus intimes.',
        reflection: 'Ce nom nous rappelle qu\'Allah connaît nos intentions et nos efforts cachés.',
        attributes: ['Expertise', 'Connaissance détaillée', 'Omniscience'],
      ),
      AllahName(
        number: 32,
        arabic: 'الحَلِيمُ',
        transliteration: 'Al-Halim',
        french: 'L\'Indulgent',
        meaning: 'Celui qui fait preuve de clémence',
        description: 'Allah est patient et ne précipite pas le châtiment.',
        reflection: 'Ce nom nous enseigne à être indulgents et patients avec autrui.',
        attributes: ['Indulgence', 'Clémence', 'Patience'],
      ),
      AllahName(
        number: 33,
        arabic: 'العَظِيمُ',
        transliteration: 'Al-Azim',
        french: 'L\'Immense',
        meaning: 'Celui dont la grandeur est infinie',
        description: 'Allah est d\'une grandeur qui dépasse toute imagination.',
        reflection: 'Méditer sur ce nom nous humilie et renforce notre vénération.',
        attributes: ['Grandeur', 'Immensité', 'Magnificence'],
      ),
      AllahName(
        number: 34,
        arabic: 'الغَفُورُ',
        transliteration: 'Al-Ghafur',
        french: 'Celui qui pardonne',
        meaning: 'Celui qui cache et pardonne les péchés',
        description: 'Allah pardonne les fautes et les couvre de Sa miséricorde.',
        reflection: 'Ce nom nous encourage au repentir sincère.',
        attributes: ['Pardon', 'Miséricorde', 'Couverture des péchés'],
      ),
      AllahName(
        number: 35,
        arabic: 'الشَّكُورُ',
        transliteration: 'Ash-Shakur',
        french: 'Le Reconnaissant',
        meaning: 'Celui qui récompense généreusement',
        description: 'Allah multiplie les récompenses pour les petites bonnes actions.',
        reflection: 'Ce nom nous inspire à être reconnaissants et à apprécier les efforts d\'autrui.',
        attributes: ['Reconnaissance', 'Récompense', 'Générosité'],
      ),
      
      // Noms 36-70 (sélection des plus importants)
      AllahName(
        number: 36,
        arabic: 'العَلِيُّ',
        transliteration: 'Al-Ali',
        french: 'Le Très-Haut',
        meaning: 'Celui qui est au-dessus de tout',
        description: 'Allah est élevé au-dessus de toute Sa création.',
        reflection: 'Ce nom nous rappelle la transcendance divine.',
        attributes: ['Élévation', 'Transcendance', 'Suprématie'],
      ),
      AllahName(
        number: 37,
        arabic: 'الكَبِيرُ',
        transliteration: 'Al-Kabir',
        french: 'Le Grand',
        meaning: 'Celui dont la grandeur est absolue',
        description: 'Allah est infiniment grand en essence et en attributs.',
        reflection: 'Méditer sur Sa grandeur nous inspire l\'humilité.',
        attributes: ['Grandeur absolue', 'Majesté', 'Infinité'],
      ),
      AllahName(
        number: 38,
        arabic: 'الحَفِيظُ',
        transliteration: 'Al-Hafiz',
        french: 'Le Gardien',
        meaning: 'Celui qui préserve et protège',
        description: 'Allah garde et protège toute Sa création.',
        reflection: 'Ce nom nous rassure sur la protection divine.',
        attributes: ['Protection', 'Préservation', 'Garde'],
      ),
      AllahName(
        number: 39,
        arabic: 'المُقِيتُ',
        transliteration: 'Al-Muqit',
        french: 'Le Nourricier',
        meaning: 'Celui qui nourrit et sustente',
        description: 'Allah pourvoit à la nourriture de toutes Ses créatures.',
        reflection: 'Ce nom renforce notre confiance en Sa providence.',
        attributes: ['Nourriture', 'Sustentation', 'Providence'],
      ),
      AllahName(
        number: 40,
        arabic: 'الحَسِيبُ',
        transliteration: 'Al-Hasib',
        french: 'Celui qui fait les comptes',
        meaning: 'Celui qui suffit à Ses serviteurs',
        description: 'Allah suffit à ceux qui placent leur confiance en Lui.',
        reflection: 'Ce nom nous encourage à nous en remettre totalement à Allah.',
        attributes: ['Suffisance', 'Confiance', 'Compte'],
      ),
      
      // Noms 41-60
      AllahName(
        number: 41,
        arabic: 'الجَلِيلُ',
        transliteration: 'Al-Jalil',
        french: 'Le Majestueux',
        meaning: 'Celui qui possède la majesté absolue',
        description: 'Allah est digne de vénération par Sa majesté.',
        reflection: 'Ce nom inspire le respect et la vénération.',
        attributes: ['Majesté', 'Vénération', 'Dignité'],
      ),
      AllahName(
        number: 42,
        arabic: 'الكَرِيمُ',
        transliteration: 'Al-Karim',
        french: 'Le Généreux',
        meaning: 'Celui qui donne sans limite',
        description: 'Allah est d\'une générosité sans borne.',
        reflection: 'Ce nom nous inspire à être généreux avec autrui.',
        attributes: ['Générosité', 'Noblesse', 'Largesse'],
      ),
      AllahName(
        number: 43,
        arabic: 'الرَّقِيبُ',
        transliteration: 'Ar-Raqib',
        french: 'Le Surveillant',
        meaning: 'Celui qui observe constamment',
        description: 'Allah surveille continuellement toutes Ses créatures.',
        reflection: 'Ce nom nous incite à bien agir sachant qu\'Allah nous observe.',
        attributes: ['Surveillance', 'Observation', 'Vigilance'],
      ),
      AllahName(
        number: 44,
        arabic: 'المُجِيبُ',
        transliteration: 'Al-Mujib',
        french: 'Celui qui exauce',
        meaning: 'Celui qui répond aux invocations',
        description: 'Allah répond aux prières de Ses serviteurs.',
        reflection: 'Ce nom nous encourage à invoquer Allah avec conviction.',
        attributes: ['Exaucement', 'Réponse', 'Invocation'],
      ),
      AllahName(
        number: 45,
        arabic: 'الوَاسِعُ',
        transliteration: 'Al-Wasi',
        french: 'L\'Ample',
        meaning: 'Celui dont l\'ampleur englobe tout',
        description: 'La miséricorde et la science d\'Allah englobent toute chose.',
        reflection: 'Ce nom nous rassure sur l\'immensité de Sa miséricorde.',
        attributes: ['Ampleur', 'Vastitude', 'Englobement'],
      ),
      
      // Noms 46-70
      AllahName(
        number: 46,
        arabic: 'الحَكِيمُ',
        transliteration: 'Al-Hakim',
        french: 'Le Sage',
        meaning: 'Celui qui possède la sagesse parfaite',
        description: 'Allah agit toujours avec une sagesse parfaite.',
        reflection: 'Ce nom nous aide à accepter ce qui nous semble difficile.',
        attributes: ['Sagesse', 'Justesse', 'Perfection'],
      ),
      AllahName(
        number: 47,
        arabic: 'الوَدُودُ',
        transliteration: 'Al-Wadud',
        french: 'Le Bienaimé',
        meaning: 'Celui qui aime et qui est aimé',
        description: 'Allah aime Ses serviteurs pieux et ils L\'aiment.',
        reflection: 'Ce nom nourrit notre amour pour Allah.',
        attributes: ['Amour', 'Affection', 'Tendresse'],
      ),
      AllahName(
        number: 48,
        arabic: 'المَجِيدُ',
        transliteration: 'Al-Majid',
        french: 'Le Glorieux',
        meaning: 'Celui qui possède la gloire parfaite',
        description: 'Allah est digne de toute gloire et louange.',
        reflection: 'Ce nom nous inspire à glorifier Allah.',
        attributes: ['Gloire', 'Louange', 'Excellence'],
      ),
      AllahName(
        number: 49,
        arabic: 'البَاعِثُ',
        transliteration: 'Al-Ba\'ith',
        french: 'Celui qui ressuscite',
        meaning: 'Celui qui ressuscite les morts',
        description: 'Allah ressuscitera tous les êtres pour le Jugement.',
        reflection: 'Ce nom nous rappelle la résurrection et l\'au-delà.',
        attributes: ['Résurrection', 'Renaissance', 'Jugement'],
      ),
      AllahName(
        number: 50,
        arabic: 'الشَّهِيدُ',
        transliteration: 'Ash-Shahid',
        french: 'Le Témoin',
        meaning: 'Celui qui témoigne de tout',
        description: 'Allah est témoin de toutes nos actions.',
        reflection: 'Ce nom nous rappelle qu\'Allah voit tout ce que nous faisons.',
        attributes: ['Témoignage', 'Présence', 'Attestation'],
      ),
      
      // Noms 71-99
      AllahName(
        number: 71,
        arabic: 'المُتَعَالِي',
        transliteration: 'Al-Muta\'ali',
        french: 'Le Très Élevé',
        meaning: 'Celui qui s\'élève au-dessus de tout',
        description: 'Allah transcende toute Sa création.',
        reflection: 'Ce nom nous inspire l\'humilité face à Sa grandeur.',
        attributes: ['Transcendance', 'Élévation suprême', 'Au-delà'],
      ),
      AllahName(
        number: 72,
        arabic: 'البَرُّ',
        transliteration: 'Al-Barr',
        french: 'Le Bienfaisant',
        meaning: 'Celui qui fait le bien',
        description: 'Allah est source de tout bien pour Ses créatures.',
        reflection: 'Ce nom nous inspire à faire le bien autour de nous.',
        attributes: ['Bienfaisance', 'Bonté', 'Bien'],
      ),
      AllahName(
        number: 73,
        arabic: 'التَّوَّابُ',
        transliteration: 'At-Tawwab',
        french: 'Celui qui agrée le repentir',
        meaning: 'Celui qui accepte le repentir',
        description: 'Allah accepte le repentir sincère de Ses serviteurs.',
        reflection: 'Ce nom nous encourage au repentir constant.',
        attributes: ['Repentir', 'Retour à Allah', 'Pardon'],
      ),
      AllahName(
        number: 74,
        arabic: 'المُنْتَقِمُ',
        transliteration: 'Al-Muntaqim',
        french: 'Le Vengeur',
        meaning: 'Celui qui châtie les injustes',
        description: 'Allah châtie ceux qui persistent dans l\'injustice.',
        reflection: 'Ce nom nous met en garde contre l\'injustice.',
        attributes: ['Justice divine', 'Châtiment', 'Rétribution'],
      ),
      AllahName(
        number: 75,
        arabic: 'العَفُوُّ',
        transliteration: 'Al-\'Afuww',
        french: 'Celui qui efface',
        meaning: 'Celui qui efface les péchés',
        description: 'Allah efface complètement les péchés pardonnés.',
        reflection: 'Ce nom nous donne espoir en la miséricorde divine.',
        attributes: ['Effacement', 'Pardon total', 'Purification'],
      ),
      AllahName(
        number: 76,
        arabic: 'الرَّؤُوفُ',
        transliteration: 'Ar-Ra\'uf',
        french: 'Le Compatissant',
        meaning: 'Celui qui a une grande compassion',
        description: 'Allah traite Ses créatures avec une immense compassion.',
        reflection: 'Ce nom nourrit notre compassion envers autrui.',
        attributes: ['Compassion', 'Tendresse', 'Pitié'],
      ),
      AllahName(
        number: 77,
        arabic: 'مَالِكُ المُلْكِ',
        transliteration: 'Malik-ul-Mulk',
        french: 'Le Possesseur du royaume',
        meaning: 'Celui qui possède tout royaume',
        description: 'Allah est le propriétaire de tous les royaumes.',
        reflection: 'Ce nom nous rappelle que tout appartient à Allah.',
        attributes: ['Propriété', 'Royaume', 'Souveraineté'],
      ),
      AllahName(
        number: 78,
        arabic: 'ذُو الجَلاَلِ وَالإكْرَامِ',
        transliteration: 'Dhul-Jalali wal-Ikram',
        french: 'Le Détenteur de la Majesté et de la Générosité',
        meaning: 'Celui qui possède majesté et générosité',
        description: 'Allah combine parfaitement majesté et générosité.',
        reflection: 'Ce nom nous inspire respect et espoir à la fois.',
        attributes: ['Majesté', 'Générosité', 'Honneur'],
      ),
      AllahName(
        number: 79,
        arabic: 'المُقْسِطُ',
        transliteration: 'Al-Muqsit',
        french: 'L\'Équitable',
        meaning: 'Celui qui établit l\'équité',
        description: 'Allah juge avec une parfaite équité.',
        reflection: 'Ce nom nous inspire à être équitables dans nos jugements.',
        attributes: ['Équité', 'Justice', 'Impartialité'],
      ),
      AllahName(
        number: 80,
        arabic: 'الجَامِعُ',
        transliteration: 'Al-Jami',
        french: 'Celui qui rassemble',
        meaning: 'Celui qui réunit toute chose',
        description: 'Allah rassemblera toutes Ses créatures le Jour du Jugement.',
        reflection: 'Ce nom nous rappelle le rassemblement final.',
        attributes: ['Rassemblement', 'Réunion', 'Unification'],
      ),
      AllahName(
        number: 81,
        arabic: 'الغَنِيُّ',
        transliteration: 'Al-Ghani',
        french: 'Celui qui Se suffit à Lui-même',
        meaning: 'Celui qui n\'a besoin de rien',
        description: 'Allah n\'a besoin de rien ni de personne.',
        reflection: 'Ce nom nous rappelle notre dépendance totale envers Allah.',
        attributes: ['Indépendance', 'Suffisance', 'Richesse absolue'],
      ),
      AllahName(
        number: 82,
        arabic: 'المُغْنِي',
        transliteration: 'Al-Mughni',
        french: 'Celui qui enrichit',
        meaning: 'Celui qui rend riche',
        description: 'Allah enrichit qui Il veut de Sa création.',
        reflection: 'Ce nom nous rappelle que la richesse vient d\'Allah.',
        attributes: ['Enrichissement', 'Abondance', 'Prospérité'],
      ),
      AllahName(
        number: 83,
        arabic: 'المَانِعُ',
        transliteration: 'Al-Mani',
        french: 'Le Défenseur',
        meaning: 'Celui qui protège et empêche',
        description: 'Allah protège Ses serviteurs et empêche le mal de les atteindre.',
        reflection: 'Ce nom nous rassure sur la protection divine.',
        attributes: ['Défense', 'Protection', 'Empêchement du mal'],
      ),
      AllahName(
        number: 84,
        arabic: 'الضَّارُ',
        transliteration: 'Ad-Darr',
        french: 'Celui qui peut nuire',
        meaning: 'Celui de qui peut venir le mal',
        description: 'Seul Allah peut permettre qu\'un mal nous atteigne.',
        reflection: 'Ce nom nous rappelle de chercher protection uniquement auprès d\'Allah.',
        attributes: ['Épreuve', 'Test', 'Permission divine'],
      ),
      AllahName(
        number: 85,
        arabic: 'النَّافِعُ',
        transliteration: 'An-Nafi',
        french: 'Celui qui accorde le profit',
        meaning: 'Celui de qui vient tout bien',
        description: 'Tout bien et profit ne peuvent venir que d\'Allah.',
        reflection: 'Ce nom nous rappelle de ne compter que sur Allah pour le bien.',
        attributes: ['Bien', 'Profit', 'Bénéfice'],
      ),
      AllahName(
        number: 86,
        arabic: 'النُّورُ',
        transliteration: 'An-Nur',
        french: 'La Lumière',
        meaning: 'Celui qui est lumière pure',
        description: 'Allah est la lumière des cieux et de la terre.',
        reflection: 'Ce nom guide notre âme vers la lumière divine.',
        attributes: ['Lumière', 'Guidance', 'Clarté'],
      ),
      AllahName(
        number: 87,
        arabic: 'الهَادِي',
        transliteration: 'Al-Hadi',
        french: 'Le Guide',
        meaning: 'Celui qui guide vers la vérité',
        description: 'Allah guide vers le droit chemin ceux qui Le cherchent.',
        reflection: 'Ce nom nous encourage à demander guidance à Allah.',
        attributes: ['Guidance', 'Direction', 'Chemin droit'],
      ),
      AllahName(
        number: 88,
        arabic: 'البَدِيعُ',
        transliteration: 'Al-Badi',
        french: 'Le Novateur',
        meaning: 'Celui qui crée de façon parfaite et nouvelle',
        description: 'Allah crée sans modèle préexistant avec une perfection absolue.',
        reflection: 'Ce nom éveille notre émerveillement devant la création.',
        attributes: ['Innovation', 'Création parfaite', 'Nouveauté'],
      ),
      AllahName(
        number: 89,
        arabic: 'البَاقِي',
        transliteration: 'Al-Baqi',
        french: 'L\'Éternel',
        meaning: 'Celui qui demeure éternellement',
        description: 'Allah subsiste éternellement alors que tout périt.',
        reflection: 'Ce nom nous rappelle la nature éphémère de ce monde.',
        attributes: ['Éternité', 'Permanence', 'Subsistance'],
      ),
      AllahName(
        number: 90,
        arabic: 'الوَارِثُ',
        transliteration: 'Al-Warith',
        french: 'L\'Héritier',
        meaning: 'Celui qui hérite de tout',
        description: 'Allah hérite de tout ce qui existe après sa disparition.',
        reflection: 'Ce nom nous rappelle que tout retourne à Allah.',
        attributes: ['Héritage', 'Retour', 'Possession finale'],
      ),
      AllahName(
        number: 91,
        arabic: 'الرَّشِيدُ',
        transliteration: 'Ar-Rashid',
        french: 'Celui qui dirige bien',
        meaning: 'Celui qui guide vers la rectitude',
        description: 'Allah dirige toute chose selon Sa sagesse parfaite.',
        reflection: 'Ce nom nous inspire à suivre la guidance divine.',
        attributes: ['Direction juste', 'Rectitude', 'Bonne guidance'],
      ),
      AllahName(
        number: 92,
        arabic: 'الصَّبُورُ',
        transliteration: 'As-Sabur',
        french: 'Le Patient',
        meaning: 'Celui qui fait preuve de patience',
        description: 'Allah patiente avec Ses créatures et ne les châtie pas immédiatement.',
        reflection: 'Ce nom nous enseigne la patience dans les épreuves et avec les autres.',
        attributes: ['Patience', 'Endurance', 'Clémence'],
      ),
      
      // Quelques noms supplémentaires pour compléter
      AllahName(
        number: 93,
        arabic: 'الحَقُّ',
        transliteration: 'Al-Haqq',
        french: 'La Vérité',
        meaning: 'Celui qui est la vérité absolue',
        description: 'Allah est la vérité pure, sans mélange de fausseté.',
        reflection: 'Ce nom nous guide vers la recherche de la vérité.',
        attributes: ['Vérité absolue', 'Réalité', 'Authenticité'],
      ),
      AllahName(
        number: 94,
        arabic: 'الوَكِيلُ',
        transliteration: 'Al-Wakil',
        french: 'Le Garant',
        meaning: 'Celui sur qui on peut compter',
        description: 'Allah est le meilleur garant pour ceux qui Lui font confiance.',
        reflection: 'Ce nom renforce notre confiance en Allah.',
        attributes: ['Garantie', 'Confiance', 'Responsabilité'],
      ),
      AllahName(
        number: 95,
        arabic: 'القَوِيُّ',
        transliteration: 'Al-Qawi',
        french: 'Le Fort',
        meaning: 'Celui qui possède la force absolue',
        description: 'Allah est d\'une force inébranlable et parfaite.',
        reflection: 'Ce nom nous rappelle de chercher la force auprès d\'Allah.',
        attributes: ['Force absolue', 'Puissance', 'Solidité'],
      ),
      AllahName(
        number: 96,
        arabic: 'المَتِينُ',
        transliteration: 'Al-Matin',
        french: 'Le Très Fort',
        meaning: 'Celui dont la force est inébranlable',
        description: 'La force d\'Allah est ferme et ne fléchit jamais.',
        reflection: 'Ce nom nous inspire à puiser notre force en Allah.',
        attributes: ['Force ferme', 'Inébranlabilité', 'Solidité parfaite'],
      ),
      AllahName(
        number: 97,
        arabic: 'الوَلِيُّ',
        transliteration: 'Al-Wali',
        french: 'Le Protecteur',
        meaning: 'Celui qui protège et gouverne',
        description: 'Allah protège et prend soin de Ses serviteurs pieux.',
        reflection: 'Ce nom nous rassure sur la protection constante d\'Allah.',
        attributes: ['Protection', 'Gouvernance', 'Proximité'],
      ),
      AllahName(
        number: 98,
        arabic: 'الحَمِيدُ',
        transliteration: 'Al-Hamid',
        french: 'Le Digne de louange',
        meaning: 'Celui qui mérite toute louange',
        description: 'Allah est digne de louange en toutes circonstances.',
        reflection: 'Ce nom nous inspire à louer Allah constamment.',
        attributes: ['Louange', 'Mérite', 'Gratitude'],
      ),
      AllahName(
        number: 99,
        arabic: 'الصَّبُورُ',
        transliteration: 'As-Sabur',
        french: 'Le Patient',
        meaning: 'Celui qui fait preuve de patience',
        description: 'Allah patiente avec Ses créatures et ne les châtie pas immédiatement.',
        reflection: 'Ce nom nous enseigne la patience dans les épreuves et avec les autres.',
        attributes: ['Patience', 'Endurance', 'Clémence'],
      ),
    ];
  }
}