import 'package:flutter/material.dart';
import 'package:sajda/models/morning_evening_dhikr.dart';

/// Rabbana invocations (duas from the Qur'an beginning with "رَبَّنَا")
/// Each item provides: Arabic, transliteration, French meaning, and verse source.
class RabbanaDuas {
  static List<DhikrItem> all() {
    return [
      DhikrItem(
        id: 'rb_2_201',
        arabicText: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
        transliteration: 'Rabbanā ātinā fī ad-dunyā ḥasanatan wa fī al-ākhirati ḥasanatan wa qinā ʿadhāba an-nār',
        meaning: 'Notre Seigneur, accorde‑nous le bien en ce monde et le bien dans l’au‑delà, et préserve‑nous du châtiment du Feu.',
        repetitions: 1,
        benefit: 'Supplication englobante pour le bien ici‑bas et dans l’au‑delà.',
        reward: 'Prière coranique très complète et bénie',
        audioUrl: 'https://example.com/audio/rabbana_2_201.mp3',
        icon: Icons.auto_awesome,
        color: const Color(0xFF4CAF50),
        category: 'Rabbana',
        source: 'Coran 2:201',
        hadithReference: null,
      ),
      DhikrItem(
        id: 'rb_2_286',
        arabicText:
            'رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
        transliteration:
            'Rabbanā lā tuʾākhidh’nā in nasīnā aw akhṭaʾnā. Rabbanā wa lā taḥmil ʿalaynā iṣ’ran kamā ḥamaltahu ʿalā alladhīna min qablina. Rabbanā wa lā tuḥammilnā mā lā ṭāqata lanā bih, waʿfu ʿannā, waghfir lanā, warḥamnā. Anta mawlānā fa‑nṣurnā ʿalā al‑qawmi al‑kāfirīn.',
        meaning:
            'Notre Seigneur, ne nous châtie pas s’il nous arrive d’oublier ou de commettre une erreur. Notre Seigneur, ne nous impose pas un fardeau comme Tu l’as imposé à ceux qui nous ont précédés. Notre Seigneur, ne nous charge pas de ce que nous ne pouvons supporter; efface nos fautes, pardonne‑nous, et fais‑nous miséricorde. Tu es notre Maître; accorde‑nous donc la victoire sur les mécréants.',
        repetitions: 1,
        benefit: 'Clôture d’Al‑Baqarah: pardon, miséricorde, allègement et victoire.',
        reward: 'Protection et miséricorde abondantes',
        audioUrl: 'https://example.com/audio/rabbana_2_286.mp3',
        icon: Icons.shield,
        color: const Color(0xFF3F51B5),
        category: 'Rabbana',
        source: 'Coran 2:286',
      ),
      DhikrItem(
        id: 'rb_3_8',
        arabicText: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً إِنَّكَ أَنتَ الْوَهَّابُ',
        transliteration: 'Rabbanā lā tuzigh qulūbanā baʿda idh hadaytanā wa hab lanā min ladunka raḥmah, innaka anta al‑Wahhāb',
        meaning: 'Notre Seigneur, ne laisse pas dévier nos cœurs après nous avoir guidés et accorde‑nous de Ta part une miséricorde. Tu es, en vérité, le Grand Donateur.',
        repetitions: 1,
        benefit: 'Fermeté sur la guidance et demande de miséricorde.',
        reward: 'Stabilité du cœur et miséricorde',
        audioUrl: 'https://example.com/audio/rabbana_3_8.mp3',
        icon: Icons.favorite,
        color: const Color(0xFFE91E63),
        category: 'Rabbana',
        source: 'Coran 3:8',
      ),
      DhikrItem(
        id: 'rb_3_16',
        arabicText: 'رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ',
        transliteration: 'Rabbanā innanā āmannā faghfir lanā dhunūbanā wa qinā ʿadhāba an‑nār',
        meaning: 'Notre Seigneur, nous avons cru; pardonne‑nous nos péchés et préserve‑nous du châtiment du Feu.',
        repetitions: 1,
        benefit: 'Liée à la foi, au pardon et à la protection contre l’Enfer.',
        reward: 'Pardon et protection',
        audioUrl: 'https://example.com/audio/rabbana_3_16.mp3',
        icon: Icons.local_fire_department,
        color: const Color(0xFFFF7043),
        category: 'Rabbana',
        source: 'Coran 3:16',
      ),
      DhikrItem(
        id: 'rb_3_53',
        arabicText: 'رَبَّنَا آمَنَّا بِمَا أَنْزَلْتَ وَاتَّبَعْنَا الرَّسُولَ فَاكْتُبْنَا مَعَ الشَّاهِدِينَ',
        transliteration: 'Rabbanā āmannā bimā anzalta wa-ttabaʿnā ar‑rasūla faktubnā maʿa ash‑shāhidīn',
        meaning: 'Notre Seigneur, nous avons cru à ce que Tu as révélé et nous avons suivi le Messager; inscris‑nous donc parmi les témoins.',
        repetitions: 1,
        benefit: 'Affirmation de foi et compagnie des véridiques.',
        reward: 'Inscription parmi les témoins véridiques',
        audioUrl: 'https://example.com/audio/rabbana_3_53.mp3',
        icon: Icons.how_to_reg,
        color: const Color(0xFF26C6DA),
        category: 'Rabbana',
        source: 'Coran 3:53',
      ),
      DhikrItem(
        id: 'rb_3_147',
        arabicText: 'رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
        transliteration:
            'Rabbanā ighfir lanā dhunūbanā wa isrāfanā fī amrinā wa thabbit aqdāmanā wa‑nṣurnā ʿalā al‑qawmi al‑kāfirīn',
        meaning:
            'Notre Seigneur, pardonne‑nous nos péchés et nos excès dans notre conduite; affermis nos pas et donne‑nous la victoire sur les mécréants.',
        repetitions: 1,
        benefit: 'Pardon, discipline, fermeté et victoire.',
        reward: 'Assistance divine dans l’épreuve',
        audioUrl: 'https://example.com/audio/rabbana_3_147.mp3',
        icon: Icons.flag,
        color: const Color(0xFF7E57C2),
        category: 'Rabbana',
        source: 'Coran 3:147',
      ),
      DhikrItem(
        id: 'rb_7_23',
        arabicText: 'رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
        transliteration: 'Rabbanā ẓalamnā anfusanā wa in lam taghfir lanā wa tarḥamnā lanakūnanna mina al‑khāsirīn',
        meaning: 'Notre Seigneur, nous nous sommes fait du tort à nous‑mêmes; et si Tu ne nous pardonnes pas et ne nous fais pas miséricorde, nous serons certes du nombre des perdants.',
        repetitions: 1,
        benefit: 'Repentance d’Adam et Hawwāʾ; modèle d’aveu et de retour.',
        reward: 'Espoir du pardon et de la miséricorde',
        audioUrl: 'https://example.com/audio/rabbana_7_23.mp3',
        icon: Icons.healing,
        color: const Color(0xFF00897B),
        category: 'Rabbana',
        source: 'Coran 7:23',
      ),
      DhikrItem(
        id: 'rb_2_250',
        arabicText: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
        transliteration: 'Rabbanā afrigh ʿalaynā ṣabran wa thabbit aqdāmanā wa‑nṣurnā ʿalā al‑qawmi al‑kāfirīn',
        meaning: 'Notre Seigneur, déverse sur nous la patience, affermis nos pas et accorde‑nous la victoire sur les mécréants.',
        repetitions: 1,
        benefit: 'Patience, fermeté et secours face à l’adversité.',
        reward: 'Assistance et victoire par la patience',
        audioUrl: 'https://example.com/audio/rabbana_2_250.mp3',
        icon: Icons.bolt,
        color: const Color(0xFFFFA726),
        category: 'Rabbana',
        source: 'Coran 2:250',
      ),
      DhikrItem(
        id: 'rb_3_193',
        arabicText:
            'رَبَّنَا إِنَّنَا سَمِعْنَا مُنَادِيًا يُنَادِي لِلإِيمَانِ أَنْ آمِنُوا بِرَبِّكُمْ فَآمَنَّا رَبَّنَا فَاغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا وَتَوَفَّنَا مَعَ الأَبْرَارِ',
        transliteration:
            'Rabbanā innanā samiʿnā munādiyan yunādī lil‑īmān an āminū bi rabbikum fa āmanna. Rabbanā faghfir lanā dhunūbanā wa kaffir ʿannā sayyiʾātinā wa tawaffanā maʿa al‑abrār',
        meaning:
            'Notre Seigneur, nous avons entendu un appelant inviter à la foi: “Croyez en votre Seigneur”; et nous avons cru. Notre Seigneur, pardonne‑nous donc nos péchés, efface nos méfaits et fais‑nous mourir avec les vertueux.',
        repetitions: 1,
        benefit: 'Réponse à l’appel de la foi, pardon et belle fin.',
        reward: 'Compagnie des vertueux',
        audioUrl: 'https://example.com/audio/rabbana_3_193.mp3',
        icon: Icons.record_voice_over,
        color: const Color(0xFF26A69A),
        category: 'Rabbana',
        source: 'Coran 3:193',
      ),
      DhikrItem(
        id: 'rb_3_194',
        arabicText: 'رَبَّنَا وَآتِنَا مَا وَعَدتَّنَا عَلَى رُسُلِكَ وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ إِنَّكَ لَا تُخْلِفُ الْمِيعَادَ',
        transliteration: 'Rabbanā wa ātinā mā waʿadtanā ʿalā rusulika wa lā tukh’zinā yawma al‑qiyāmah, innaka lā tukhlifu al‑mīʿād',
        meaning: 'Notre Seigneur, accorde‑nous ce que Tu nous as promis par l’intermédiaire de Tes messagers et ne nous couvre pas d’ignominie au Jour de la Résurrection. Tu ne manques jamais à Ta promesse.',
        repetitions: 1,
        benefit: 'Espoir dans la promesse divine et dignité au Jour Dernier.',
        reward: 'Promesse accomplie et honneur',
        audioUrl: 'https://example.com/audio/rabbana_3_194.mp3',
        icon: Icons.verified,
        color: const Color(0xFF5C6BC0),
        category: 'Rabbana',
        source: 'Coran 3:194',
      ),
      DhikrItem(
        id: 'rb_14_40_41',
        arabicText:
            'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي ۚ رَبَّنَا وَتَقَبَّلْ دُعَاءِ ﴿٤٠﴾ رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ ﴿٤١﴾',
        transliteration:
            'Rabbi ijʿalnī muqīma aṣ‑ṣalāh wa min dhurriyyatī. Rabbanā wa taqabbal duʿāʾ. Rabbanā ighfir lī wa liwālidayya wa lil‑muʾminīna yawma yaqūmu al‑ḥisāb',
        meaning:
            'Seigneur, fais de moi quelqu’un qui accomplit la prière, ainsi que de ma descendance. Notre Seigneur, accepte ma supplication. Notre Seigneur, pardonne‑moi, à mes parents et aux croyants, le jour où se fera le compte.',
        repetitions: 1,
        benefit: 'Prière, descendance pieuse et pardon pour soi, parents et croyants.',
        reward: 'Acceptation et pardon général',
        audioUrl: 'https://example.com/audio/rabbana_14_40_41.mp3',
        icon: Icons.family_restroom,
        color: const Color(0xFF8D6E63),
        category: 'Rabbana',
        source: 'Coran 14:40‑41',
      ),
      DhikrItem(
        id: 'rb_25_65_66',
        arabicText:
            'رَبَّنَا اصْرِفْ عَنَّا عَذَابَ جَهَنَّمَ إِنَّ عَذَابَهَا كَانَ غَرَامًا ﴿٦٥﴾ إِنَّهَا سَاءَتْ مُسْتَقَرًّا وَمُقَامًا ﴿٦٦﴾',
        transliteration:
            'Rabbanā iṣ’rif ʿannā ʿadhāba Jahannam, inna ʿadhābahā kāna gharāmā. Innahā sāʾat mustaqarran wa muqāmā',
        meaning:
            'Notre Seigneur, écarte de nous le châtiment de la Géhenne; son châtiment est certes un tourment permanent. Quel détestable séjour et lieu de résidence!',
        repetitions: 1,
        benefit: 'Crainte d’Allah, fuite de l’Enfer et recherche du salut.',
        reward: 'Protection contre la Géhenne',
        audioUrl: 'https://example.com/audio/rabbana_25_65_66.mp3',
        icon: Icons.highlight_off,
        color: const Color(0xFFD32F2F),
        category: 'Rabbana',
        source: 'Coran 25:65‑66',
      ),
      DhikrItem(
        id: 'rb_25_74',
        arabicText: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
        transliteration: 'Rabbanā hab lanā min azwājinā wa dhurriyyātinā qurrata aʿyunin wa‑jʿalnā lil‑muttaqīna imāmā',
        meaning: 'Notre Seigneur, accorde‑nous en nos épouses et nos descendants la joie des yeux, et fais de nous un guide pour les pieux.',
        repetitions: 1,
        benefit: 'Famille apaisée et leadership dans la piété.',
        reward: 'Joie familiale et exemplarité',
        audioUrl: 'https://example.com/audio/rabbana_25_74.mp3',
        icon: Icons.child_care,
        color: const Color(0xFF66BB6A),
        category: 'Rabbana',
        source: 'Coran 25:74',
      ),
      DhikrItem(
        id: 'rb_59_10',
        arabicText:
            'رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا لِّلَّذِينَ آمَنُوا رَبَّنَا إِنَّكَ رَءُوفٌ رَّحِيمٌ',
        transliteration:
            'Rabbanā ighfir lanā wa li ikh’wāninā alladhīna sabaqūnā bil‑īmān wa lā tajʿal fī qulūbinā ghillan lilladhīna āmanū. Rabbanā innaka raʾūfun raḥīm',
        meaning:
            'Notre Seigneur, pardonne‑nous ainsi qu’à nos frères qui nous ont précédés dans la foi; et ne mets pas dans nos cœurs de rancune pour ceux qui ont cru. Notre Seigneur, Tu es Compatissant, Miséricordieux.',
        repetitions: 1,
        benefit: 'Purification du cœur et fraternité des croyants.',
        reward: 'Pardon et cœur sain',
        audioUrl: 'https://example.com/audio/rabbana_59_10.mp3',
        icon: Icons.group,
        color: const Color(0xFF42A5F5),
        category: 'Rabbana',
        source: 'Coran 59:10',
      ),
      DhikrItem(
        id: 'rb_60_5',
        arabicText: 'رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلَّذِينَ كَفَرُوا وَاغْفِرْ لَنَا رَبَّنَا إِنَّكَ أَنتَ الْعَزِيزُ الْحَكِيمُ',
        transliteration: 'Rabbanā lā tajʿalnā fitnatan lilladhīna kafarū waghfir lanā rabbanā innaka anta al‑ʿazīzu al‑ḥakīm',
        meaning: 'Notre Seigneur, ne fais pas de nous une tentation pour ceux qui ne croient pas; et pardonne‑nous, notre Seigneur. Tu es certes le Tout‑Puissant, le Sage.',
        repetitions: 1,
        benefit: 'Protection contre l’épreuve, dignité et pardon.',
        reward: 'Sauvegarde et sagesse',
        audioUrl: 'https://example.com/audio/rabbana_60_5.mp3',
        icon: Icons.balance,
        color: const Color(0xFF8E24AA),
        category: 'Rabbana',
        source: 'Coran 60:5',
      ),
      DhikrItem(
        id: 'rb_66_8',
        arabicText:
            'رَبَّنَا أَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
        transliteration:
            'Rabbanā atmim lanā nūranā waghfir lanā, innaka ʿalā kulli shayʾin qadīr',
        meaning: 'Notre Seigneur, parachève pour nous notre lumière et pardonne‑nous; Tu es, certes, capable de toute chose.',
        repetitions: 1,
        benefit: 'Parachèvement de la lumière et pardon au Jour Dernier.',
        reward: 'Lumière parfaite et pardon',
        audioUrl: 'https://example.com/audio/rabbana_66_8.mp3',
        icon: Icons.light_mode,
        color: const Color(0xFFFFC107),
        category: 'Rabbana',
        source: 'Coran 66:8',
      ),
      DhikrItem(
        id: 'rb_23_118',
        arabicText: 'وَقُل رَّبِّ اغْفِرْ وَارْحَمْ وَأَنتَ خَيْرُ الرَّاحِمِينَ',
        transliteration: 'Wa qul rabbi ighfir wa rḥam wa anta khayru ar‑rāḥimīn',
        meaning: 'Et dis: Seigneur, pardonne et fais miséricorde; Tu es le Meilleur des miséricordieux.',
        repetitions: 1,
        benefit: 'Clôture d’Al‑Muʾminūn: pardon et miséricorde.',
        reward: 'Pardon et miséricorde',
        audioUrl: 'https://example.com/audio/rabbana_23_118.mp3',
        icon: Icons.favorite_border,
        color: const Color(0xFFEC407A),
        category: 'Rabbana',
        source: 'Coran 23:118',
      ),
      // ——— Ajouts pour compléter la liste à 50 invocations ———
      DhikrItem(
        id: 'rb_2_127',
        arabicText: 'رَبَّنَا تَقَبَّلْ مِنَّا ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ',
        transliteration: 'Rabbanā taqabbal minnā, innaka anta as‑Samīʿu al‑ʿAlīm',
        meaning: 'Notre Seigneur, accepte ceci de notre part. Tu es, en vérité, l’Audient, l’Omniscient.',
        repetitions: 1,
        benefit: 'Supplication d’Ibrâhîm et Ismâʿīl lors de l’élévation des fondations de la Kaʿbah.',
        reward: 'Acceptation des œuvres',
        audioUrl: 'https://example.com/audio/rabbana_2_127.mp3',
        icon: Icons.home,
        color: Color(0xFF5E35B1),
        category: 'Rabbana',
        source: 'Coran 2:127',
      ),
      DhikrItem(
        id: 'rb_2_128',
        arabicText:
            'رَبَّنَا وَاجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِنْ ذُرِّيَّتِنَا أُمَّةً مُّسْلِمَةً لَّكَ وَأَرِنَا مَنَاسِكَنَا وَتُبْ عَلَيْنَا ۖ إِنَّكَ أَنتَ التَّوَّابُ الرَّحِيمُ',
        transliteration:
            'Rabbanā wajʿalnā muslimayn laka wa min dhurriyyatinā ummatan muslimatan laka, wa arinā manāsikanā wa tub ʿalaynā, innaka anta at‑Tawwābu ar‑Raḥīm',
        meaning:
            'Notre Seigneur, fais de nous des soumis à Toi, et de notre descendance une communauté soumise à Toi; montre‑nous nos rites et accepte notre repentir. Tu es certes Celui qui agrée le repentir, le Très Miséricordieux.',
        repetitions: 1,
        benefit: 'Soumission, guidance rituelle et repentir accepté.',
        reward: 'Guidance et miséricorde',
        audioUrl: 'https://example.com/audio/rabbana_2_128.mp3',
        icon: Icons.self_improvement,
        color: Color(0xFF00897B),
        category: 'Rabbana',
        source: 'Coran 2:128',
      ),
      DhikrItem(
        id: 'rb_2_129',
        arabicText:
            'رَّبَّنَا وَابْعَثْ فِيهِمْ رَسُولًا مِّنْهُمْ يَتْلُوا۟ عَلَيْهِمْ ءَايَٰتِكَ وَيُعَلِّمُهُمُ ٱلْكِتَٰبَ وَٱلْحِكْمَةَ وَيُزَكِّيهِمْ ۚ إِنَّكَ أَنتَ ٱلْعَزِيزُ ٱلْحَكِيمُ',
        transliteration:
            'Rabbanā wabʿath fīhim rasūlan min’hum yatlū ʿalayhim āyātika wa yuʿallimuhumu al‑kitāba wal‑ḥikmata wa yuzakkīhim, innaka anta al‑ʿAzīzu al‑Ḥakīm',
        meaning:
            'Notre Seigneur, envoie parmi eux un Messager issu d’eux qui leur récitera Tes versets, leur enseignera le Livre et la sagesse et les purifiera. Tu es le Tout‑Puissant, le Sage.',
        repetitions: 1,
        benefit: 'Prière pour l’envoi du Messager et la purification.',
        reward: 'Science bénéfique et épuration des âmes',
        audioUrl: 'https://example.com/audio/rabbana_2_129.mp3',
        icon: Icons.menu_book,
        color: Color(0xFF6D4C41),
        category: 'Rabbana',
        source: 'Coran 2:129',
      ),
      DhikrItem(
        id: 'rb_3_9',
        arabicText:
            'رَبَّنَا إِنَّكَ جَامِعُ ٱلنَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ ۚ إِنَّ ٱللَّهَ لَا يُخْلِفُ ٱلْمِيعَادَ',
        transliteration:
            'Rabbanā innaka jāmiʿu an‑nāsi li yawmin lā rayba fīh, inna Allāha lā yukhlifu al‑mīʿād',
        meaning:
            'Notre Seigneur, Tu rassembleras les gens pour un Jour au sujet duquel il n’y a point de doute. Allah ne manque jamais à Sa promesse.',
        repetitions: 1,
        benefit: 'Foi au Jour Dernier et confiance en la promesse divine.',
        reward: 'Fermeté de la certitude',
        audioUrl: 'https://example.com/audio/rabbana_3_9.mp3',
        icon: Icons.schedule,
        color: Color(0xFF3949AB),
        category: 'Rabbana',
        source: 'Coran 3:9',
      ),
      DhikrItem(
        id: 'rb_3_191',
        arabicText:
            'رَبَّنَا مَا خَلَقْتَ هَٰذَا بَاطِلًا سُبْحَٰنَكَ فَقِنَا عَذَابَ ٱلنَّارِ',
        transliteration:
            'Rabbanā mā khalaqta hādhā bāṭilan, subḥānaka, faq’inā ʿadhāba an‑nār',
        meaning: 'Notre Seigneur, Tu n’as pas créé cela en vain. Gloire à Toi! Préserve‑nous donc du châtiment du Feu.',
        repetitions: 1,
        benefit: 'Contemplation de la création et recherche du salut.',
        reward: 'Protection contre le Feu',
        audioUrl: 'https://example.com/audio/rabbana_3_191.mp3',
        icon: Icons.public,
        color: Color(0xFF00796B),
        category: 'Rabbana',
        source: 'Coran 3:191',
      ),
      DhikrItem(
        id: 'rb_5_83',
        arabicText: 'رَبَّنَا آمَنَّا فَٱكْتُبْنَا مَعَ ٱلشَّٰهِدِينَ',
        transliteration: 'Rabbanā āmannā fa‑ktubnā maʿa ash‑shāhidīn',
        meaning: 'Notre Seigneur, nous avons cru; inscris‑nous donc parmi les témoins.',
        repetitions: 1,
        benefit: 'Foi sincère et témoignage de la vérité.',
        reward: 'Compagnie des véridiques',
        audioUrl: 'https://example.com/audio/rabbana_5_83.mp3',
        icon: Icons.how_to_reg,
        color: Color(0xFF00ACC1),
        category: 'Rabbana',
        source: 'Coran 5:83',
      ),
      DhikrItem(
        id: 'rb_7_47',
        arabicText: 'رَبَّنَا لَا تَجْعَلْنَا مَعَ ٱلْقَوْمِ ٱلظَّٰلِمِينَ',
        transliteration: 'Rabbanā lā tajʿalnā maʿa al‑qawmi aẓ‑ẓālimīn',
        meaning: 'Notre Seigneur, ne nous mets pas avec le peuple des injustes.',
        repetitions: 1,
        benefit: 'Éloignement de l’injustice et de ses gens.',
        reward: 'Sauvegarde contre l’injustice',
        audioUrl: 'https://example.com/audio/rabbana_7_47.mp3',
        icon: Icons.block,
        color: Color(0xFF8D6E63),
        category: 'Rabbana',
        source: 'Coran 7:47',
      ),
      DhikrItem(
        id: 'rb_7_89',
        arabicText:
            'رَبَّنَا ٱفْتَحْ بَيْنَنَا وَبَيْنَ قَوْمِنَا بِٱلْحَقِّ وَأَنتَ خَيْرُ ٱلْفَاتِحِينَ',
        transliteration:
            'Rabbanā iftaḥ baynanā wa bayna qawminā bil‑ḥaqq, wa anta khayru al‑fātiḥīn',
        meaning: 'Notre Seigneur, tranche entre nous et notre peuple en toute vérité; Tu es le Meilleur des juges.',
        repetitions: 1,
        benefit: 'Arbitrage juste et issue favorable.',
        reward: 'Victoire par la justice',
        audioUrl: 'https://example.com/audio/rabbana_7_89.mp3',
        icon: Icons.gavel,
        color: Color(0xFF6A1B9A),
        category: 'Rabbana',
        source: 'Coran 7:89',
      ),
      DhikrItem(
        id: 'rb_7_126',
        arabicText: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ',
        transliteration: 'Rabbanā afrigh ʿalaynā ṣabran wa tawaffanā muslimīn',
        meaning: 'Notre Seigneur, déverse sur nous une patience inébranlable et fais‑nous mourir soumis à Toi.',
        repetitions: 1,
        benefit: 'Patience dans l’épreuve et belle fin.',
        reward: 'Fermeté et bonne issue',
        audioUrl: 'https://example.com/audio/rabbana_7_126.mp3',
        icon: Icons.battery_full,
        color: Color(0xFF43A047),
        category: 'Rabbana',
        source: 'Coran 7:126',
      ),
      DhikrItem(
        id: 'rb_7_156',
        arabicText:
            'رَبَّنَا ٱكْتُبْ لَنَا فِى هَٰذِهِ ٱلدُّنْيَا حَسَنَةً وَفِى ٱلْـَٔاخِرَةِ إِنَّا هُدْنَآ إِلَيْكَ',
        transliteration:
            'Rabbanā uktub lanā fī hādhihi ad‑dunyā ḥasanatan wa fī al‑ākhirah, innā hudnā ilayk',
        meaning:
            'Notre Seigneur, inscris‑nous une belle part de bonheur ici‑bas et dans l’au‑delà; nous revenons repentants vers Toi.',
        repetitions: 1,
        benefit: 'Bien ici‑bas et dans l’au‑delà, avec repentir.',
        reward: 'Part bénie et miséricorde',
        audioUrl: 'https://example.com/audio/rabbana_7_156.mp3',
        icon: Icons.assignment_turned_in,
        color: Color(0xFFEF6C00),
        category: 'Rabbana',
        source: 'Coran 7:156',
      ),
      DhikrItem(
        id: 'rb_10_85',
        arabicText: 'رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلْقَوْمِ ٱلظَّٰلِمِينَ',
        transliteration: 'Rabbanā lā tajʿalnā fitnatan lil‑qawmi aẓ‑ẓālimīn',
        meaning: 'Notre Seigneur, ne fais pas de nous une tentation pour les gens injustes.',
        repetitions: 1,
        benefit: 'Dignité et protection contre l’oppression.',
        reward: 'Sauvegarde contre les injustes',
        audioUrl: 'https://example.com/audio/rabbana_10_85.mp3',
        icon: Icons.shield_moon,
        color: Color(0xFF5C6BC0),
        category: 'Rabbana',
        source: 'Coran 10:85',
      ),
      DhikrItem(
        id: 'rb_10_86',
        arabicText: 'وَنَجِّنَا بِرَحْمَتِكَ مِنَ ٱلْقَوْمِ ٱلْكَٰفِرِينَ',
        transliteration: 'Wa najjinā biraḥmatika mina al‑qawmi al‑kāfirīn',
        meaning: 'Et sauve‑nous, par Ta miséricorde, du peuple des mécréants.',
        repetitions: 1,
        benefit: 'Secours et salut face aux ennemis de la foi.',
        reward: 'Délivrance miséricordieuse',
        audioUrl: 'https://example.com/audio/rabbana_10_86.mp3',
        icon: Icons.sailing,
        color: Color(0xFF0097A7),
        category: 'Rabbana',
        source: 'Coran 10:86',
      ),
      DhikrItem(
        id: 'rb_14_38',
        arabicText:
            'رَبَّنَا إِنَّكَ تَعْلَمُ مَا نُخْفِي وَمَا نُعْلِنُ وَمَا يَخْفَىٰ عَلَى ٱللَّهِ مِن شَيْءٍ فِي ٱلْأَرْضِ وَلَا فِي ٱلسَّمَاءِ',
        transliteration:
            'Rabbanā innaka taʿlamu mā nukhfī wa mā nuʿlin, wa mā yakhfā ʿalā Allāhi min shayʾin fī al‑arḍi wa lā fī as‑samāʾ',
        meaning: 'Notre Seigneur, Tu sais ce que nous cachons et ce que nous divulguons. Rien n’échappe à Allah sur terre ni dans le ciel.',
        repetitions: 1,
        benefit: 'Conscience d’Allah et sincérité.',
        reward: 'Sincérité intérieure',
        audioUrl: 'https://example.com/audio/rabbana_14_38.mp3',
        icon: Icons.visibility,
        color: Color(0xFF7CB342),
        category: 'Rabbana',
        source: 'Coran 14:38',
      ),
      DhikrItem(
        id: 'rb_18_10',
        arabicText:
            'رَبَّنَا آتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا',
        transliteration: 'Rabbanā ātinā min ladunka raḥmah wa hayyiʾ lanā min amrinā rashadā',
        meaning: 'Notre Seigneur, accorde‑nous de Ta part une miséricorde et dispose pour nous la droiture dans notre situation.',
        repetitions: 1,
        benefit: 'Miséricorde et rectitude dans la voie.',
        reward: 'Guidance et clarté',
        audioUrl: 'https://example.com/audio/rabbana_18_10.mp3',
        icon: Icons.explore,
        color: Color(0xFF558B2F),
        category: 'Rabbana',
        source: 'Coran 18:10',
      ),
      DhikrItem(
        id: 'rb_20_45',
        arabicText: 'رَبَّنَا إِنَّنَا نَخَافُ أَن يَفْرُطَ عَلَيْنَا أَوْ أَن يَطْغَىٰ',
        transliteration: 'Rabbanā innanā nakhāfu an yafruta ʿalaynā aw an yaṭghā',
        meaning: 'Notre Seigneur, nous craignons qu’il ne s’emporte contre nous ou qu’il ne transgresse.',
        repetitions: 1,
        benefit: 'Appui divin avant d’affronter les tyrans (invocation de Mūsā et Hārūn).',
        reward: 'Assurance et protection',
        audioUrl: 'https://example.com/audio/rabbana_20_45.mp3',
        icon: Icons.warning_amber,
        color: Color(0xFF8E24AA),
        category: 'Rabbana',
        source: 'Coran 20:45',
      ),
      
      DhikrItem(
        id: 'rb_23_97_98',
        arabicText:
            'قُلْ رَبِّ أَعُوذُ بِكَ مِنْ هَمَزَٰتِ ٱلشَّيَٰطِينِ ﴿٩٧﴾ وَأَعُوذُ بِكَ رَبِّ أَن يَحْضُرُونِ ﴿٩٨﴾',
        transliteration:
            'Qul: Rabbi aʿūdhu bika min hamazāti ash‑shayāṭīn (97). Wa aʿūdhu bika Rabbi an yaḥḍurūn (98)',
        meaning: 'Dis: Seigneur, je cherche protection auprès de Toi contre les suggestions des diables; et je cherche protection auprès de Toi, Seigneur, pour qu’ils ne m’approchent pas.',
        repetitions: 1,
        benefit: 'Protection contre les diables et leurs insinuations.',
        reward: 'Préservation spirituelle',
        audioUrl: 'https://example.com/audio/rabbana_23_97_98.mp3',
        icon: Icons.shield_outlined,
        color: Color(0xFF546E7A),
        category: 'Rabbana',
        source: 'Coran 23:97‑98',
      ),
      
      DhikrItem(
        id: 'rb_28_16',
        arabicText: 'رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَٱغْفِرْ لِي',
        transliteration: 'Rabbi innī ẓalamtu nafsī fa‑ghfir lī',
        meaning: 'Seigneur, j’ai fait du tort à moi‑même; pardonne‑moi.',
        repetitions: 1,
        benefit: 'Reconnaissance de la faute et pardon demandé (Mūsā).',
        reward: 'Pardon et miséricorde',
        audioUrl: 'https://example.com/audio/rabbana_28_16.mp3',
        icon: Icons.clean_hands,
        color: Color(0xFF4E342E),
        category: 'Rabbana',
        source: 'Coran 28:16',
      ),
      DhikrItem(
        id: 'rb_28_24',
        arabicText: 'رَبِّ إِنِّي لِمَآ أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ',
        transliteration: 'Rabbi innī limā anzalta ilayya min khayrin faqīr',
        meaning: 'Seigneur, j’ai grand besoin du bien que Tu feras descendre vers moi.',
        repetitions: 1,
        benefit: 'Reconnaissance de la pauvreté devant Allah et espoir en Sa grâce.',
        reward: 'Provision bénie',
        audioUrl: 'https://example.com/audio/rabbana_28_24.mp3',
        icon: Icons.volunteer_activism,
        color: Color(0xFF00695C),
        category: 'Rabbana',
        source: 'Coran 28:24',
      ),
      DhikrItem(
        id: 'rb_37_100',
        arabicText: 'رَبِّ هَبْ لِي مِنَ ٱلصَّٰلِحِينَ',
        transliteration: 'Rabbi hab lī mina aṣ‑ṣāliḥīn',
        meaning: 'Seigneur, accorde‑moi [une descendance] d’entre les vertueux.',
        repetitions: 1,
        benefit: 'Demande de descendance pieuse (Ibrâhîm).',
        reward: 'Enfants vertueux',
        audioUrl: 'https://example.com/audio/rabbana_37_100.mp3',
        icon: Icons.baby_changing_station,
        color: Color(0xFF2E7D32),
        category: 'Rabbana',
        source: 'Coran 37:100',
      ),
      DhikrItem(
        id: 'rb_38_35',
        arabicText:
            'رَبِّ ٱغْفِرْ لِي وَهَبْ لِي مُلْكًا لَّا يَنبَغِي لِأَحَدٍ مِّنۢ بَعْدِي ۖ إِنَّكَ أَنتَ ٱلْوَهَّابُ',
        transliteration:
            'Rabbi ighfir lī wa hab lī mulkan lā yanbaghī li‑aḥadin min baʿdī, innaka anta al‑Wahhāb',
        meaning: 'Seigneur, pardonne‑moi et accorde‑moi une royauté telle que nul après moi ne devra posséder. Tu es certes le Grand Donateur.',
        repetitions: 1,
        benefit: 'Pardon et don exceptionnel (Sulaymān).',
        reward: 'Pardon et largesse',
        audioUrl: 'https://example.com/audio/rabbana_38_35.mp3',
        icon: Icons.king_bed,
        color: Color(0xFF512DA8),
        category: 'Rabbana',
        source: 'Coran 38:35',
      ),
      DhikrItem(
        id: 'rb_40_7',
        arabicText:
            'رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَّحْمَةً وَعِلْمًا فَٱغْفِرْ لِلَّذِينَ تَابُوا۟ وَٱتَّبَعُوا۟ سَبِيلَكَ وَقِهِمْ عَذَابَ ٱلْجَحِيمِ',
        transliteration:
            'Rabbanā wasiʿta kulla shayʾin raḥmatan wa ʿilman fa‑ghfir lilladhīna tābū wa‑ttabaʿū sabīlak wa qi’him ʿadhāba al‑jaḥīm',
        meaning: 'Notre Seigneur, Tu embrasses toute chose de miséricorde et de science; pardonne donc à ceux qui se sont repentis et ont suivi Ton chemin, et préserve‑les du châtiment de la Fournaise.',
        repetitions: 1,
        benefit: 'Invocation des anges en faveur des croyants.',
        reward: 'Pardon et protection',
        audioUrl: 'https://example.com/audio/rabbana_40_7.mp3',
        icon: Icons.cloud,
        color: Color(0xFF1565C0),
        category: 'Rabbana',
        source: 'Coran 40:7',
      ),
      DhikrItem(
        id: 'rb_40_8',
        arabicText:
            'رَبَّنَا وَأَدْخِلْهُمْ جَنَّاتِ عَدْنٍ ٱلَّتِي وَعَدتَّهُمْ وَمَن صَلَحَ مِنْ آبَآئِهِمْ وَأَزْوَٰجِهِمْ وَذُرِّيَّاتِهِمْ ۚ إِنَّكَ أَنتَ ٱلْعَزِيزُ ٱلْحَكِيمُ',
        transliteration:
            'Rabbanā wa adkhilhumu jannāti ʿadnin allatī waʿadttahum wa man ṣalaḥa min ābāʾihim wa azwājihim wa dhurriyyātihim, innaka anta al‑ʿAzīzu al‑Ḥakīm',
        meaning:
            'Notre Seigneur, fais‑les entrer aux Jardins d’Éden que Tu leur as promis, ainsi que les vertueux parmi leurs pères, leurs épouses et leurs descendants. Tu es certes le Tout‑Puissant, le Sage.',
        repetitions: 1,
        benefit: 'Entrée au Paradis pour soi et sa famille vertueuse.',
        reward: 'Admission au Paradis',
        audioUrl: 'https://example.com/audio/rabbana_40_8.mp3',
        icon: Icons.park,
        color: Color(0xFF2E7D32),
        category: 'Rabbana',
        source: 'Coran 40:8',
      ),
      DhikrItem(
        id: 'rb_40_9',
        arabicText:
            'وَقِهِمُ ٱلسَّيِّـَٔاتِ ۚ وَمَن تَقِ ٱلسَّيِّـَٔاتِ يَوْمَئِذٍ فَقَدْ رَحِمْتَهُۥ ۚ وَذَٰلِكَ هُوَ ٱلْفَوْزُ ٱلْعَظِيمُ',
        transliteration:
            'Wa qi’himu as‑sayyiʾāt, wa man taqi as‑sayyiʾāti yawmaʾidhin faqad raḥimtah, wa dhālika huwa al‑fawzu al‑ʿaẓīm',
        meaning: 'Et préserve‑les des mauvaises actions. Quiconque Tu préserves ce jour‑là des mauvaises actions, Tu lui as fait miséricorde. Voilà la réussite suprême.',
        repetitions: 1,
        benefit: 'Protection finale au Jour Dernier.',
        reward: 'Réussite suprême',
        audioUrl: 'https://example.com/audio/rabbana_40_9.mp3',
        icon: Icons.emoji_events,
        color: Color(0xFF37474F),
        category: 'Rabbana',
        source: 'Coran 40:9',
      ),
      DhikrItem(
        id: 'rb_46_15',
        arabicText:
            'رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ ٱلَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَىٰهُ وَأَصْلِحْ لِي فِي ذُرِّيَّتِي إِنِّي تُبْتُ إِلَيْكَ وَإِنِّي مِنَ ٱلْمُسْلِمِينَ',
        transliteration:
            'Rabbi awziʿnī an ashkura niʿmataka allatī anʿamta ʿalayya wa ʿalā wālidayya wa an aʿmala ṣāliḥan tarḍāh, wa aṣliḥ lī fī dhurriyyatī, innī tubtu ilayk wa innī mina al‑muslimīn',
        meaning:
            'Seigneur, inspire‑moi à te remercier pour Tes bienfaits dont Tu m’as comblé ainsi que mes parents, et à faire une œuvre pie qui Te satisfasse. Améliore ma descendance pour moi. Je me repens à Toi et je suis du nombre des soumis.',
        repetitions: 1,
        benefit: 'Reconnaissance, œuvres agréées et réforme de la descendance.',
        reward: 'Gratitude et piété familiale',
        audioUrl: 'https://example.com/audio/rabbana_46_15.mp3',
        icon: Icons.auto_fix_high,
        color: Color(0xFF9E9D24),
        category: 'Rabbana',
        source: 'Coran 46:15',
      ),
      DhikrItem(
        id: 'rb_60_4',
        arabicText:
            'رَبَّنَا عَلَيْكَ تَوَكَّلْنَا وَإِلَيْكَ أَنَبْنَا وَإِلَيْكَ ٱلْمَصِيرُ',
        transliteration: 'Rabbanā ʿalayka tawakkalnā wa ilayka anabnā wa ilayka al‑maṣīr',
        meaning: 'Notre Seigneur, c’est en Toi que nous plaçons notre confiance; vers Toi nous revenons repentants, et vers Toi est le devenir.',
        repetitions: 1,
        benefit: 'Tawakkul, repentir et conscience de l’Au‑delà.',
        reward: 'Confiance et retour vers Allah',
        audioUrl: 'https://example.com/audio/rabbana_60_4.mp3',
        icon: Icons.trending_up,
        color: Color(0xFF1E88E5),
        category: 'Rabbana',
        source: 'Coran 60:4',
      ),
      DhikrItem(
        id: 'rb_66_11',
        arabicText: 'رَبِّ ٱبْنِ لِي عِندَكَ بَيْتًا فِي ٱلْجَنَّةِ',
        transliteration: 'Rabbi ibni lī ʿindaka baytan fī al‑jannah',
        meaning: 'Seigneur, bâtis‑moi auprès de Toi une maison au Paradis.',
        repetitions: 1,
        benefit: 'Invocation de la femme de Pharaon – aspiration au Paradis.',
        reward: 'Demeure au Paradis',
        audioUrl: 'https://example.com/audio/rabbana_66_11.mp3',
        icon: Icons.house,
        color: Color(0xFF6D4C41),
        category: 'Rabbana',
        source: 'Coran 66:11',
      ),
      DhikrItem(
        id: 'rb_3_35',
        arabicText:
            'رَبِّ إِنِّي نَذَرْتُ لَكَ مَا فِي بَطْنِي مُحَرَّرًا فَتَقَبَّلْ مِنِّي ۖ إِنَّكَ أَنتَ ٱلسَّمِيعُ ٱلْعَلِيمُ',
        transliteration:
            'Rabbi innī nadhartu laka mā fī baṭnī muḥarraran fa‑taqabbal minnī, innaka anta as‑Samīʿu al‑ʿAlīm',
        meaning: 'Seigneur, je T’ai voué en toute exclusivité ce que je porte en mon ventre. Accepte‑le de moi. Tu es l’Audient, l’Omniscient.',
        repetitions: 1,
        benefit: 'Sincérité du vœu (mère de Maryam).',
        reward: 'Acceptation du vœu',
        audioUrl: 'https://example.com/audio/rabbana_3_35.mp3',
        icon: Icons.favorite,
        color: Color(0xFFE53935),
        category: 'Rabbana',
        source: 'Coran 3:35',
      ),
      DhikrItem(
        id: 'rb_3_36',
        arabicText:
            'وَإِنِّي سَمَّيْتُهَا مَرْيَمَ وَإِنِّيٓ أُعِيذُهَا بِكَ وَذُرِّيَّتَهَا مِنَ ٱلشَّيْطَٰنِ ٱلرَّجِيمِ',
        transliteration:
            'Wa innī sammaytuhā Maryam, wa innī uʿīdhuhā bika wa dhurriyyatahā mina ash‑shayṭāni ar‑rajīm',
        meaning: 'Et je l’ai appelée Maryam, et je la place, ainsi que sa descendance, sous Ta protection contre le diable le banni.',
        repetitions: 1,
        benefit: 'Protection des enfants contre Satan.',
        reward: 'Préservation des enfants',
        audioUrl: 'https://example.com/audio/rabbana_3_36.mp3',
        icon: Icons.child_friendly,
        color: Color(0xFFAB47BC),
        category: 'Rabbana',
        source: 'Coran 3:36',
      ),
      DhikrItem(
        id: 'rb_12_101',
        arabicText:
            'رَبِّ قَدْ آتَيْتَنِي مِنَ ٱلْمُلْكِ وَعَلَّمْتَنِي مِن تَأْوِيلِ ٱلْأَحَادِيثِ ۚ فَاطِرَ ٱلسَّمَٰوَاتِ وَٱلْأَرْضِ ۖ أَنتَ وَلِيِّي فِي ٱلدُّنْيَا وَٱلْـَٔاخِرَةِ ۖ تَوَفَّنِي مُسْلِمًا وَأَلْحِقْنِي بِٱلصَّالِحِينَ',
        transliteration:
            'Rabbi qad ātaytanī mina al‑mulki wa ʿallamtanī min taʾwīli al‑aḥādīth. Fāṭira as‑samāwāti wal‑arḍ, anta waliyyī fī ad‑dunyā wal‑ākhirah, tawaffanī musliman wa alḥiqnī biṣ‑ṣāliḥīn',
        meaning:
            'Seigneur, Tu m’as donné une part de royauté et Tu m’as appris l’interprétation des rêves. Créateur des cieux et de la terre, Tu es mon Protecteur ici‑bas et dans l’au‑delà. Fais‑moi mourir soumis, et fais‑moi rejoindre les vertueux.',
        repetitions: 1,
        benefit: 'Gratitude, tawḥīd et belle fin (Yūsuf).',
        reward: 'Bonne fin et compagnie des pieux',
        audioUrl: 'https://example.com/audio/rabbana_12_101.mp3',
        icon: Icons.star,
        color: Color(0xFFFF8F00),
        category: 'Rabbana',
        source: 'Coran 12:101',
      ),
      
      DhikrItem(
        id: 'rb_4_75',
        arabicText:
            'رَبَّنَآ أَخْرِجْنَا مِنْ هَٰذِهِ ٱلْقَرْيَةِ ٱلظَّالِمِ أَهْلُهَا وَٱجْعَل لَّنَا مِن لَّدُنكَ وَلِيًّا وَٱجْعَل لَّنَا مِن لَّدُنكَ نَصِيرًا',
        transliteration:
            'Rabbanā akhrijnā min hādhihi al‑qaryati aẓ‑ẓālimi ahluhā, wa‑jʿal lanā min ladunka waliyyan wa‑jʿal lanā min ladunka naṣīrā',
        meaning:
            'Notre Seigneur, fais‑nous sortir de cette cité dont les habitants sont injustes; et assigne‑nous de Ta part un allié et de Ta part un secoureur.',
        repetitions: 1,
        benefit: 'Délivrance de l’oppression et soutien divin.',
        reward: 'Secours et protection',
        audioUrl: 'https://example.com/audio/rabbana_4_75.mp3',
        icon: Icons.directions_run,
        color: Color(0xFFD32F2F),
        category: 'Rabbana',
        source: 'Coran 4:75',
      ),
      
      DhikrItem(
        id: 'rb_71_28',
        arabicText: 'رَّبِّ ٱغْفِرْ لِي وَلِوَالِدَيَّ وَلِمَن دَخَلَ بَيْتِيَ مُؤْمِنًا وَلِلْمُؤْمِنِينَ وَٱلْمُؤْمِنَاتِ',
        transliteration:
            'Rabbi ighfir lī wa li‑wālidayya wa liman dakhala baytiya muʾminan wa lil‑muʾminīna wal‑muʾmināt',
        meaning: 'Seigneur, pardonne‑moi ainsi qu’à mes père et mère, à quiconque entre chez moi croyant, et aux croyants et croyantes.',
        repetitions: 1,
        benefit: 'Pardon pour soi, ses parents et la communauté.',
        reward: 'Pardon étendu',
        audioUrl: 'https://example.com/audio/rabbana_71_28.mp3',
        icon: Icons.group_add,
        color: Color(0xFF1976D2),
        category: 'Rabbana',
        source: 'Coran 71:28',
      ),
      
      DhikrItem(
        id: 'rb_3_38',
        arabicText: 'رَبِّ هَبْ لِي مِن لَّدُنكَ ذُرِّيَّةً طَيِّبَةً إِنَّكَ سَمِيعُ ٱلدُّعَآءِ',
        transliteration: 'Rabbi hab lī min ladunka dhurriyyatan ṭayyibah, innaka samīʿu ad‑duʿāʾ',
        meaning: 'Seigneur, accorde‑moi, de Ta part, une bonne descendance. Tu es, certes, Celui qui entend la prière.',
        repetitions: 1,
        benefit: 'Demande d’enfant pieux (Zakariyyā).',
        reward: 'Descendance pieuse',
        audioUrl: 'https://example.com/audio/rabbana_3_38.mp3',
        icon: Icons.escalator_warning,
        color: Color(0xFF6A1B9A),
        category: 'Rabbana',
        source: 'Coran 3:38',
      ),
      // 50) Complément — Invocation de Moussa (7:151)
      DhikrItem(
        id: 'rb_7_151',
        arabicText:
            'قَالَ رَبِّ ٱغْفِرْ لِي وَلِأَخِي وَأَدْخِلْنَا فِي رَحْمَتِكَ وَأَنتَ أَرْحَمُ ٱلرَّاحِمِينَ',
        transliteration:
            'Qāla: Rabbi ighfir lī wa li‑akhī wa adkhilnā fī raḥmatik, wa anta arḥamu ar‑rāḥimīn',
        meaning:
            'Il dit: Seigneur, pardonne‑moi ainsi qu’à mon frère; fais‑nous entrer en Ta miséricorde. Tu es le plus miséricordieux des miséricordieux.',
        repetitions: 1,
        benefit: 'Pardon et miséricorde invoqués par Moussa (paix sur lui).',
        reward: 'Pardon, fraternité et miséricorde divine',
        audioUrl: 'https://example.com/audio/rabbana_7_151.mp3',
        icon: Icons.handshake,
        color: Color(0xFF1B5E20),
        category: 'Rabbana',
        source: 'Coran 7:151',
      ),
    ];
  }
}
