import 'package:flutter/material.dart';
import 'package:sajda/models/morning_evening_dhikr.dart';

class AdditionalDhikr {
  static List<DhikrItem> getProphetBlessings() {
    return [
      DhikrItem(
        id: 'salawat_full_complete',
        arabicText: 'اللَّهُمَّ صَلِّ صَلاَةً كَامِلَةً وَأَنِم نَوْمًا هَانِئًا عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ وَبَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ',
        transliteration: '''Allāhumma ṣalli ṣalāatan kāmilatan wa anim nawman hāni'an ʿalā Muḥammadin wa ʿalā āli Muḥammadin kamā ṣallayta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm wa bārik ʿalā Muḥammadin wa ʿalā āli Muḥammadin kamā bārakta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm innaka ḥamīdun majīd.''',
        meaning: 'Ô Allah, accorde une prière complète et un repos agréable à Muhammad et à sa famille comme Tu l\'as accordé à Ibrahim et sa famille, et bénis Muhammad et sa famille comme Tu as béni Ibrahim et sa famille; Tu es Digne de louanges, Glorieux.',
        repetitions: 3,
        benefit: 'Prière honneur complet unissant louange, bénédiction et repos pour le Prophète.',
        reward: 'Énorme récompense et intercession du Prophète',
        audioUrl: 'https://example.com/audio/salawat_complete.mp3',
        icon: Icons.star_rate,
        color: const Color(0xFFFFD700),
        category: 'Prières Complètes',
        source: 'Sunna',
        hadithReference: 'Prière de salat complète',
      ),
      DhikrItem(
        id: 'salawat_with_names',
        arabicText: 'اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ عَبْدِكَ وَرَسُولِكَ وَنَبِيِّكَ وَخَلِيلِكَ وَحَبِيبِكَ وَخِيَارِ خَلْقِكَ، يَا أَحْكَمَ الْحَاكِمِينَ',
        transliteration: '''Allāhumma ṣalli ʿalā sayyidinā Muḥammadin ʿabdika wa rasūlika wa nabiyyika wa khalīlika wa ḥabībika wa khiyāri khalqika, yā aḥkama al-ḥākimīn.''',
        meaning: 'Ô Allah, prie sur notre maître Muhammad Ton serviteur, Ton messager, Ton prophète, Ton ami intime, Ton bien-aimé et le meilleur de Tes créatures, Ô Le Plus Sage des juges.',
        repetitions: 5,
        benefit: 'Énumération des titres honorifiques du Prophète ﷺ multipliant la prière.',
        reward: 'Honneur du Prophète et faveur divine',
        audioUrl: 'https://example.com/audio/salawat_names.mp3',
        icon: Icons.card_giftcard,
        color: const Color(0xFF9C27B0),
        category: 'Prières Complètes',
        source: 'Hadith authentique',
        hadithReference: 'Supplication des titres du Prophète',
      ),
      DhikrItem(
        id: 'salawat_hashasiyya',
        arabicText: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ فِي الْآخِرَةِ، وَصَلِّ عَلَى مُحَمَّدٍ فِي الدُّنْيَا، وَصَلِّ عَلَى مُحَمَّدٍ فِي كُلِّ وَقْتٍ وَحِينٍ',
        transliteration: '''Allāhumma ṣalli ʿalā Muḥammadin fī al-ākhirah wa ṣalli ʿalā Muḥammadin fī ad-dunyā wa ṣalli ʿalā Muḥammadin fī kulli waqtin wa ḥīn.''',
        meaning: 'Ô Allah, prie sur Muhammad dans l\'au-delà et prie sur Muhammad en ce monde, et prie sur Muhammad à tout moment et toute heure.',
        repetitions: 3,
        benefit: 'Couvre tous les temps: cette vie, l\'au-delà et chaque instant.',
        reward: 'Prières continues et éternelles',
        audioUrl: 'https://example.com/audio/salawat_hashasiyya.mp3',
        icon: Icons.schedule,
        color: const Color(0xFF00796B),
        category: 'Prières Complètes',
        source: 'Hadith traditionnel',
        hadithReference: 'Prière intemporelle',
      ),
    ];
  }

  static List<DhikrItem> getProtectiveVerses() {
    return [
      DhikrItem(
        id: 'surah_waqiah',
        arabicText: 'سُورَةُ الْوَاقِعَةِ - بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ إِذَا وَقَعَتِ الْوَاقِعَةُ ‎﴿١﴾ لَيْسَ لِوَقْعَتِهَا كَاذِبَةٌ ‎﴿٢﴾ خَافِضَةٌ رَّافِعَةٌ ‎﴿٣﴾',
        transliteration: '''Sūratu al-Wāqiʿah - Bismillāhi-r-raḥmāni-r-raḥīm. Idhā waqaʿati al-wāqiʿah laysa li waqʿatihā kādhiba khāfidatun rāfiʿah''',
        meaning: 'Sourate Al-Waqiah - Au nom d\'Allah, le Clément, le Miséricordieux. Quand l\'Événement inévitable surviendra, il n\'y a personne qui puisse le nier. Il abaisse les uns et élève les autres.',
        repetitions: 1,
        benefit: 'Récitée chaque nuit, procure subsistance abondante et protection contre la pauvreté.',
        reward: 'Richesse spirituelle et matérielle',
        audioUrl: 'https://example.com/audio/surah_waqiah.mp3',
        icon: Icons.attach_money,
        color: const Color(0xFF4CAF50),
        category: 'Surahs Protectrices',
        source: 'Coran 56:1-3',
        hadithReference: 'Hadith rapporté sur la sourate Al-Waqiah',
      ),
      DhikrItem(
        id: 'ayat_bayyinah',
        arabicText: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أُولَـٰئِكَ هُمْ خَيْرُ الْبَرِيَّةِ ‎﴿٧﴾',
        transliteration: '''Bismillāhi-r-raḥmāni-r-raḥīm. Inna alladhīna āmanū wa ʿamilū aṣ-ṣāliḥāti ūlā'ika hum khayru al-bariyyah.''',
        meaning: 'Au nom d\'Allah, le Clément, le Miséricordieux. Ceux qui ont cru et accompli de bonnes œuvres, ce sont les meilleurs de la création.',
        repetitions: 3,
        benefit: 'Renforce la foi, encourage les bonnes actions et crée une conscience d\'excellence.',
        reward: 'Élévation du rang parmi les créatures',
        audioUrl: 'https://example.com/audio/ayat_bayyinah.mp3',
        icon: Icons.people,
        color: const Color(0xFF3F51B5),
        category: 'Surahs Protectrices',
        source: 'Coran 98:7',
        hadithReference: 'Verset du honneur',
      ),
      DhikrItem(
        id: 'ayat_kahf_beginning',
        arabicText: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الْحَمْدُ لِلَّهِ الَّذِي أَنزَلَ عَلَىٰ عَبْدِهِ الْكِتَابَ وَلَمْ يَجْعَل لَّهُ عِوَجَا ‎﴿١﴾ قَيِّمًا لِّيُنذِرَ بَأْسًا شَدِيدًا مِّن لَّدُنْهُ وَيُبَشِّرَ الْمُؤْمِنِينَ ‎﴿٢﴾',
        transliteration: '''Bismillāhi-r-raḥmāni-r-raḥīm. Al-ḥamdu lillāhi alladhī anzala ʿalā ʿabdihi al-kitāb wa lam yajʿal lahu ʿiwaja qayyiman liyundhira ba'san shadīdan min ladunhu wa yubashshira al-mu'minīn.''',
        meaning: 'Au nom d\'Allah, le Clément, le Miséricordieux. Louange à Allah qui a révélé le Livre à Son serviteur et n\'y a mis aucune ambiguïté. Un livre droit pour avertir d\'un terrible châtiment venant de Lui, et annoncer aux croyants qui accomplissent de bonnes œuvres une belle récompense.',
        repetitions: 1,
        benefit: 'Début de la sourate Al-Kahf protège contre les fitnas (épreuves) et renforce la guidance.',
        reward: 'Protection contre les tentations et l\'égarement',
        audioUrl: 'https://example.com/audio/surah_kahf_beginning.mp3',
        icon: Icons.shield,
        color: const Color(0xFF536DFE),
        category: 'Surahs Protectrices',
        source: 'Coran 18:1-2',
        hadithReference: 'Sourate Al-Kahf',
      ),
      DhikrItem(
        id: 'last_two_verses_quran',
        arabicText: 'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ',
        transliteration: '''Āmana ar-rasūlu bimā unzila ilayhi min rabbihi wa-l-mu'minūn. Kullun āmana billāhi wa malā'ikatih wa kutubihi wa rusulih. Lā nufarriqu bayna aḥadin min rusulih.''',
        meaning: 'Le Messager a cru à ce qui a été révélé de la part de son Seigneur, ainsi que les croyants. Tous ont cru en Allah, Ses anges, Ses Livres et Ses Prophètes. Nous ne faisons de distinction entre aucun de Ses Prophètes.',
        repetitions: 1,
        benefit: 'Derniers versets du Coran - protègent et procurent la bénédiction complète.',
        reward: 'Récompense massive et protection',
        audioUrl: 'https://example.com/audio/last_verses_quran.mp3',
        icon: Icons.library_books,
        color: const Color(0xFF2196F3),
        category: 'Surahs Protectrices',
        source: 'Coran 2:285',
        hadithReference: 'Derniers versets du Coran',
      ),
    ];
  }

  static List<DhikrItem> getDailySupplications() {
    return [
      DhikrItem(
        id: 'dua_quran_learning',
        arabicText: 'اللَّهُمَّ اشْرَحْ لِي صَدْرِي، وَيَسِّرْ لِي أَمْرِي، وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي، يَفْقَهُوا قَوْلِي',
        transliteration: '''Allāhumma ishraḥ lī ṣadrī wa yassir lī amrī wa-ḥlul ʿuqdatan min lisānī yafqahū qawlī.''',
        meaning: 'Ô Allah, élargis ma poitrine, facilite-moi mes affaires, et délies un nœud de ma langue afin qu\'on comprenne ma parole.',
        repetitions: 3,
        benefit: 'Supplication pour la clarté, l\'aisance dans les affaires et l\'éloquence.',
        reward: 'Sagesse et facilité',
        audioUrl: 'https://example.com/audio/dua_quran.mp3',
        icon: Icons.school,
        color: const Color(0xFF673AB7),
        category: 'Supplications Quotidiennes',
        source: 'Coran 20:25-28',
        hadithReference: 'Prière de Musa',
      ),
      DhikrItem(
        id: 'dua_forgiveness_all',
        arabicText: 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، أَوَّلَهُ وَآخِرَهُ، عَلَانِيَتَهُ وَسِرَّهُ',
        transliteration: '''Allāhumma ighfir lī dhanbī kullahu diqquhu wa jillahu awwalahu wa ākhirahu ʿalāniyatahu wa sirrahu.''',
        meaning: 'Ô Allah, pardonne-moi tous mes péchés, les petits et les grands, les premiers et les derniers, ceux publics et ceux secrets.',
        repetitions: 3,
        benefit: 'Demande le pardon complet couvrant tous les aspects des péchés.',
        reward: 'Pardon complet et rémission',
        audioUrl: 'https://example.com/audio/dua_forgiveness.mp3',
        icon: Icons.favorite,
        color: const Color(0xFFE91E63),
        category: 'Supplications Quotidiennes',
        source: 'Hadith authentique',
        hadithReference: 'Prière de repentance',
      ),
      DhikrItem(
        id: 'dua_protection_family',
        arabicText: 'اللَّهُمَّ احْفَظْ لِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي',
        transliteration: 'Allāhumma iḥfaẓ lī dīnī wa dunyāya wa ahlī wa mālī',
        meaning: 'Ô Allah, protège ma religion, mon monde, ma famille et mon bien.',
        repetitions: 3,
        benefit: 'Supplication englobante pour la protection de tous les aspects importants de la vie.',
        reward: 'Protection complète de la vie et de la famille',
        audioUrl: 'https://example.com/audio/dua_protection.mp3',
        icon: Icons.family_restroom,
        color: const Color(0xFF009688),
        category: 'Supplications Quotidiennes',
        source: 'Hadith du Prophète ﷺ',
        hadithReference: 'Supplication de protection',
      ),
      DhikrItem(
        id: 'dua_patience',
        arabicText: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
        transliteration: 'Rabbanā ātinā fī ad-dunyā ḥasanatan wa fī al-ākhirati ḥasanatan wa qinā ʿadhāba an-nār',
        meaning: 'Notre Seigneur, accorde-nous le bien en ce monde et le bien dans l\'au-delà, et préserve-nous du châtiment du Feu.',
        repetitions: 3,
        benefit: 'Supplique complète cherchant les biens matériels, spirituels et la protection de l\'Enfer.',
        reward: 'Bien dans cette vie et dans l\'au-delà',
        audioUrl: 'https://example.com/audio/dua_patience.mp3',
        icon: Icons.self_improvement,
        color: const Color(0xFF4CAF50),
        category: 'Supplications Quotidiennes',
        source: 'Coran 2:201',
        hadithReference: 'Supplication Quranique',
      ),
      DhikrItem(
        id: 'dua_truthfulness',
        arabicText: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الثَّبَاتَ فِي الْأَمْرِ، وَالْعَزِيمَةَ عَلَى الرُّشْدِ، وَأَسْأَلُكَ شُكْرَ نِعْمَتِكَ، وَحُسْنَ عِبَادَتِكَ',
        transliteration: '''Allāhumma innī as'aluka ath-thābata fī al-amr wa-l-ʿazīmata ʿalā ar-rushd wa as'aluka shukra niʿmatika wa ḥusna ʿibādatik.''',
        meaning: 'Ô Allah, je Te demande la fermeté dans l\'engagement, la détermination à suivre le droit chemin, et je Te demande la gratitude pour tes bienfaits et l\'excellence dans Ton adoration.',
        repetitions: 3,
        benefit: 'Demande la stabilité morale, la gratitude et l\'excellence spirituelle.',
        reward: 'Fermeté et excellence dans la foi',
        audioUrl: 'https://example.com/audio/dua_truthfulness.mp3',
        icon: Icons.trending_up,
        color: const Color(0xFFFF6F00),
        category: 'Supplications Quotidiennes',
        source: 'Hadith rapporté',
        hadithReference: 'Supplication du Prophète ﷺ',
      ),
    ];
  }
}
