import 'package:flutter/material.dart';

class SpiritualBadge {
  final String id;
  final String name;
  final String arabicName;
  final String description;
  final IconData icon;
  final Color color;
  final int requiredHassanat;
  final bool isUnlocked;
  final DateTime? unlockedDate;
  final String category;

  SpiritualBadge({
    required this.id,
    required this.name,
    required this.arabicName,
    required this.description,
    required this.icon,
    required this.color,
    required this.requiredHassanat,
    this.isUnlocked = false,
    this.unlockedDate,
    this.category = 'General',
  });

  SpiritualBadge copyWith({
    String? id,
    String? name,
    String? arabicName,
    String? description,
    IconData? icon,
    Color? color,
    int? requiredHassanat,
    bool? isUnlocked,
    DateTime? unlockedDate,
    String? category,
  }) {
    return SpiritualBadge(
      id: id ?? this.id,
      name: name ?? this.name,
      arabicName: arabicName ?? this.arabicName,
      description: description ?? this.description,
      icon: icon ?? this.icon,
      color: color ?? this.color,
      requiredHassanat: requiredHassanat ?? this.requiredHassanat,
      isUnlocked: isUnlocked ?? this.isUnlocked,
      unlockedDate: unlockedDate ?? this.unlockedDate,
      category: category ?? this.category,
    );
  }

  static List<SpiritualBadge> getDefaultBadges() {
    return [
      // Badges de base (1-10)
      SpiritualBadge(
        id: 'first_prayer',
        name: 'Première Prière',
        arabicName: 'أول صلاة',
        description: 'Accomplir votre première prière',
        icon: Icons.star_outline,
        color: const Color(0xFFD4AF37),
        requiredHassanat: 10,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'first_step',
        name: 'Premier Pas',
        arabicName: 'الخطوة الأولى',
        description: 'Commencer votre voyage spirituel',
        icon: Icons.flag,
        color: const Color(0xFF4CAF50),
        requiredHassanat: 1,
        category: 'Débutant',
      ),
      SpiritualBadge(
        id: 'early_bird',
        name: 'Lève-tôt',
        arabicName: 'المبكر',
        description: 'Accomplir Fajr pendant 3 jours',
        icon: Icons.wb_sunny,
        color: const Color(0xFFFF9800),
        requiredHassanat: 45,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'night_guardian',
        name: 'Gardien de la nuit',
        arabicName: 'حارس الليل',
        description: 'Accomplir Isha pendant 5 jours',
        icon: Icons.nights_stay,
        color: const Color(0xFF3F51B5),
        requiredHassanat: 75,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'generous_start',
        name: 'Cœur Généreux',
        arabicName: 'القلب الكريم',
        description: 'Faire votre premier don',
        icon: Icons.volunteer_activism,
        color: const Color(0xFF9C27B0),
        requiredHassanat: 20,
        category: 'Charité',
      ),
      SpiritualBadge(
        id: 'quran_beginner',
        name: 'Lecteur du Coran',
        arabicName: 'قارئ القرآن',
        description: 'Lire le Coran pour la première fois',
        icon: Icons.menu_book,
        color: const Color(0xFF1B5E20),
        requiredHassanat: 15,
        category: 'Coran',
      ),
      SpiritualBadge(
        id: 'dhikr_starter',
        name: 'Débutant en Dhikr',
        arabicName: 'مبتدئ الذكر',
        description: 'Réciter du dhikr 5 fois',
        icon: Icons.favorite,
        color: const Color(0xFFE91E63),
        requiredHassanat: 25,
        category: 'Dhikr',
      ),
      SpiritualBadge(
        id: 'helper',
        name: 'Aide Précieuse',
        arabicName: 'المساعد الثمين',
        description: 'Aider quelqu\'un pour la première fois',
        icon: Icons.handshake,
        color: const Color(0xFF00BCD4),
        requiredHassanat: 30,
        category: 'Aide',
      ),
      SpiritualBadge(
        id: 'thankful',
        name: 'Reconnaissant',
        arabicName: 'الشاكر',
        description: 'Exprimer sa gratitude 10 fois',
        icon: Icons.sentiment_satisfied_alt,
        color: const Color(0xFFFFC107),
        requiredHassanat: 40,
        category: 'Gratitude',
      ),
      SpiritualBadge(
        id: 'truth_seeker',
        name: 'Chercheur de Vérité',
        arabicName: 'باحث الحقيقة',
        description: 'Étudier l\'Islam pendant 1 heure',
        icon: Icons.search,
        color: const Color(0xFF795548),
        requiredHassanat: 35,
        category: 'Étude',
      ),

      // Badges intermédiaires (11-50)
      SpiritualBadge(
        id: 'prayer_streak_7',
        name: 'Fidèle Adorateur',
        arabicName: 'المؤمن المخلص',
        description: '7 jours consécutifs de prières',
        icon: Icons.local_fire_department,
        color: const Color(0xFFFF6B35),
        requiredHassanat: 105,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'charity_lover',
        name: 'Amoureux de la Charité',
        arabicName: 'محب الصدقة',
        description: 'Faire 10 dons',
        icon: Icons.favorite_border,
        color: const Color(0xFFE57373),
        requiredHassanat: 200,
        category: 'Charité',
      ),
      SpiritualBadge(
        id: 'quran_regular',
        name: 'Lecteur Régulier',
        arabicName: 'القارئ المنتظم',
        description: 'Lire le Coran 10 fois',
        icon: Icons.auto_stories,
        color: const Color(0xFF388E3C),
        requiredHassanat: 150,
        category: 'Coran',
      ),
      SpiritualBadge(
        id: 'dhikr_master',
        name: 'Maître du Dhikr',
        arabicName: 'سيد الذكر',
        description: 'Réciter le dhikr 50 fois',
        icon: Icons.psychology,
        color: const Color(0xFFAB47BC),
        requiredHassanat: 125,
        category: 'Dhikr',
      ),
      SpiritualBadge(
        id: 'community_helper',
        name: 'Serviteur Communautaire',
        arabicName: 'خادم المجتمع',
        description: 'Aider 15 personnes',
        icon: Icons.groups,
        color: const Color(0xFF26C6DA),
        requiredHassanat: 300,
        category: 'Aide',
      ),
      SpiritualBadge(
        id: 'morning_warrior',
        name: 'Guerrier du Matin',
        arabicName: 'محارب الصباح',
        description: 'Se lever pour Fajr 15 jours',
        icon: Icons.wb_twilight,
        color: const Color(0xFFFFB74D),
        requiredHassanat: 225,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'patient_soul',
        name: 'Âme Patiente',
        arabicName: 'الروح الصابرة',
        description: 'Pratiquer la patience 20 fois',
        icon: Icons.self_improvement,
        color: const Color(0xFF81C784),
        requiredHassanat: 180,
        category: 'Spiritualité',
      ),
      SpiritualBadge(
        id: 'forgiver',
        name: 'Celui qui Pardonne',
        arabicName: 'الغفور',
        description: 'Pardonner à 10 personnes',
        icon: Icons.handshake,
        color: const Color(0xFFBA68C8),
        requiredHassanat: 250,
        category: 'Spiritualité',
      ),
      SpiritualBadge(
        id: 'kind_heart',
        name: 'Cœur Bienveillant',
        arabicName: 'القلب الرحيم',
        description: 'Faire 25 actes de gentillesse',
        icon: Icons.emoji_emotions,
        color: const Color(0xFFFF8A65),
        requiredHassanat: 275,
        category: 'Gentillesse',
      ),
      SpiritualBadge(
        id: 'wisdom_seeker',
        name: 'Chercheur de Sagesse',
        arabicName: 'طالب الحكمة',
        description: 'Lire 20 hadiths',
        icon: Icons.lightbulb,
        color: const Color(0xFFFDD835),
        requiredHassanat: 160,
        category: 'Étude',
      ),
      SpiritualBadge(
        id: 'fast_keeper',
        name: 'Gardien du Jeûne',
        arabicName: 'حافظ الصيام',
        description: 'Jeûner 5 jours',
        icon: Icons.dining_outlined,
        color: const Color(0xFF5C6BC0),
        requiredHassanat: 125,
        category: 'Jeûne',
      ),
      SpiritualBadge(
        id: 'night_worshipper',
        name: 'Adorateur Nocturne',
        arabicName: 'المتهجد',
        description: 'Prier Tahajjud 10 fois',
        icon: Icons.bedtime,
        color: const Color(0xFF3F51B5),
        requiredHassanat: 200,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'family_devoted',
        name: 'Dévoué à la Famille',
        arabicName: 'بار الوالدين',
        description: 'Honorer parents 30 fois',
        icon: Icons.family_restroom,
        color: const Color(0xFFE91E63),
        requiredHassanat: 450,
        category: 'Famille',
      ),
      SpiritualBadge(
        id: 'prophet_lover',
        name: 'Amoureux du Prophète',
        arabicName: 'محب الرسول',
        description: 'Réciter 100 Salawat',
        icon: Icons.auto_awesome,
        color: const Color(0xFF66BB6A),
        requiredHassanat: 300,
        category: 'Prophète',
      ),
      SpiritualBadge(
        id: 'repentant',
        name: 'Repentant',
        arabicName: 'التواب',
        description: 'Faire Tawbah 50 fois',
        icon: Icons.favorite_border,
        color: const Color(0xFFFF7043),
        requiredHassanat: 200,
        category: 'Repentir',
      ),

      // Badges avancés (51-80)
      SpiritualBadge(
        id: 'prayer_perfectionist',
        name: 'Perfectionniste de la Prière',
        arabicName: 'مثقن الصلاة',
        description: '30 jours consécutifs de prières',
        icon: Icons.stars,
        color: const Color(0xFFD4AF37),
        requiredHassanat: 450,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'charity_champion',
        name: 'Champion de la Charité',
        arabicName: 'بطل الصدقة',
        description: 'Donner 50 fois',
        icon: Icons.celebration,
        color: const Color(0xFF8BC34A),
        requiredHassanat: 1000,
        category: 'Charité',
      ),
      SpiritualBadge(
        id: 'quran_lover',
        name: 'Amoureux du Coran',
        arabicName: 'عاشق القرآن',
        description: 'Lire le Coran 50 fois',
        icon: Icons.library_books,
        color: const Color(0xFF2E7D32),
        requiredHassanat: 750,
        category: 'Coran',
      ),
      SpiritualBadge(
        id: 'dhikr_expert',
        name: 'Expert en Dhikr',
        arabicName: 'خبير الذكر',
        description: 'Réciter dhikr 200 fois',
        icon: Icons.casino,
        color: const Color(0xFF7B1FA2),
        requiredHassanat: 500,
        category: 'Dhikr',
      ),
      SpiritualBadge(
        id: 'community_leader',
        name: 'Leader Communautaire',
        arabicName: 'قائد المجتمع',
        description: 'Organiser 10 événements',
        icon: Icons.groups_2,
        color: const Color(0xFF00ACC1),
        requiredHassanat: 800,
        category: 'Leadership',
      ),
      SpiritualBadge(
        id: 'midnight_prayer',
        name: 'Prieur de Minuit',
        arabicName: 'مصلي منتصف الليل',
        description: 'Prier à minuit 20 fois',
        icon: Icons.dark_mode,
        color: const Color(0xFF1A237E),
        requiredHassanat: 600,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'hadith_scholar',
        name: 'Érudit en Hadith',
        arabicName: 'عالم الحديث',
        description: 'Étudier 100 hadiths',
        icon: Icons.school,
        color: const Color(0xFF6D4C41),
        requiredHassanat: 500,
        category: 'Étude',
      ),
      SpiritualBadge(
        id: 'fasting_master',
        name: 'Maître du Jeûne',
        arabicName: 'أستاذ الصيام',
        description: 'Jeûner 30 jours',
        icon: Icons.restaurant_menu,
        color: const Color(0xFF673AB7),
        requiredHassanat: 750,
        category: 'Jeûne',
      ),
      SpiritualBadge(
        id: 'peaceful_soul',
        name: 'Âme Paisible',
        arabicName: 'الروح المسالمة',
        description: 'Méditer 100 fois',
        icon: Icons.spa,
        color: const Color(0xFF4DB6AC),
        requiredHassanat: 400,
        category: 'Spiritualité',
      ),
      SpiritualBadge(
        id: 'teacher_of_islam',
        name: 'Enseignant Islam',
        arabicName: 'معلم الإسلام',
        description: 'Enseigner 25 fois',
        icon: Icons.cast_for_education,
        color: const Color(0xFFFFB300),
        requiredHassanat: 625,
        category: 'Enseignement',
      ),
      SpiritualBadge(
        id: 'humble_servant',
        name: 'Serviteur Humble',
        arabicName: 'العبد المتواضع',
        description: 'Pratiquer humilité 50 fois',
        icon: Icons.volunteer_activism,
        color: const Color(0xFF8D6E63),
        requiredHassanat: 500,
        category: 'Spiritualité',
      ),
      SpiritualBadge(
        id: 'grateful_heart',
        name: 'Cœur Reconnaissant',
        arabicName: 'القلب الشاكر',
        description: 'Remercier Allah 200 fois',
        icon: Icons.favorite_outline,
        color: const Color(0xFFFF5722),
        requiredHassanat: 400,
        category: 'Gratitude',
      ),

      // Badges d'excellence (81-100)
      SpiritualBadge(
        id: 'spiritual_warrior',
        name: 'Guerrier Spirituel',
        arabicName: 'المحارب الروحاني',
        description: 'Atteindre 1000 hassanat',
        icon: Icons.shield,
        color: const Color(0xFF3F51B5),
        requiredHassanat: 1000,
        category: 'Excellence',
      ),
      SpiritualBadge(
        id: 'pillar_of_faith',
        name: 'Pilier de la Foi',
        arabicName: 'عمود الإيمان',
        description: 'Accomplir tous les piliers 100 fois',
        icon: Icons.architecture,
        color: const Color(0xFF1565C0),
        requiredHassanat: 1500,
        category: 'Piliers',
      ),
      SpiritualBadge(
        id: 'quran_memorizer',
        name: 'Hafiz du Coran',
        arabicName: 'حافظ القرآن',
        description: 'Mémoriser 10 sourates',
        icon: Icons.psychology_alt,
        color: const Color(0xFF2E7D32),
        requiredHassanat: 2000,
        category: 'Coran',
      ),
      SpiritualBadge(
        id: 'charity_king',
        name: 'Roi de la Charité',
        arabicName: 'ملك الصدقة',
        description: 'Donner 100 fois',
        icon: Icons.workspace_premium,
        color: const Color(0xFFFFD700),
        requiredHassanat: 2000,
        category: 'Charité',
      ),
      SpiritualBadge(
        id: 'prayer_master',
        name: 'Maître de la Prière',
        arabicName: 'سيد الصلاة',
        description: '100 jours de prières parfaites',
        icon: Icons.military_tech,
        color: const Color(0xFFD84315),
        requiredHassanat: 1500,
        category: 'Prières',
      ),
      SpiritualBadge(
        id: 'ramadan_champion',
        name: 'Champion Ramadan',
        arabicName: 'بطل رمضان',
        description: 'Jeûner tout Ramadan',
        icon: Icons.emoji_events,
        color: const Color(0xFF7B1FA2),
        requiredHassanat: 870,
        category: 'Ramadan',
      ),
      SpiritualBadge(
        id: 'hajj_pilgrim',
        name: 'Pèlerin du Hajj',
        arabicName: 'حاج بيت الله',
        description: 'Accomplir le Hajj',
        icon: Icons.home_outlined,
        color: const Color(0xFF4A148C),
        requiredHassanat: 5000,
        category: 'Hajj',
      ),
      SpiritualBadge(
        id: 'umrah_traveler',
        name: 'Voyageur Umrah',
        arabicName: 'معتمر',
        description: 'Accomplir la Umrah',
        icon: Icons.flight_takeoff,
        color: const Color(0xFF00695C),
        requiredHassanat: 3000,
        category: 'Umrah',
      ),
      SpiritualBadge(
        id: 'scholar_supreme',
        name: 'Érudit Suprême',
        arabicName: 'العالم الأعظم',
        description: 'Étudier 1000 heures',
        icon: Icons.menu_book_outlined,
        color: const Color(0xFF5D4037),
        requiredHassanat: 3000,
        category: 'Étude',
      ),
      SpiritualBadge(
        id: 'community_builder',
        name: 'Bâtisseur Communauté',
        arabicName: 'باني المجتمع',
        description: 'Créer une mosquée/école',
        icon: Icons.domain,
        color: const Color(0xFF795548),
        requiredHassanat: 10000,
        category: 'Construction',
      ),
      SpiritualBadge(
        id: 'islamic_ambassador',
        name: 'Ambassadeur Islam',
        arabicName: 'سفير الإسلام',
        description: 'Convertir 10 personnes',
        icon: Icons.public,
        color: const Color(0xFF8BC34A),
        requiredHassanat: 5000,
        category: 'Dawah',
      ),
      SpiritualBadge(
        id: 'orphan_guardian',
        name: 'Gardien Orphelins',
        arabicName: 'كافل اليتيم',
        description: 'Parrainer 5 orphelins',
        icon: Icons.child_care,
        color: const Color(0xFFFF5722),
        requiredHassanat: 2500,
        category: 'Orphelins',
      ),
      SpiritualBadge(
        id: 'water_provider',
        name: 'Pourvoyeur d\'Eau',
        arabicName: 'ساقي الماء',
        description: 'Construire 3 puits',
        icon: Icons.water_drop,
        color: const Color(0xFF03A9F4),
        requiredHassanat: 7500,
        category: 'Eau',
      ),
      SpiritualBadge(
        id: 'knowledge_spreader',
        name: 'Propagateur Savoir',
        arabicName: 'ناشر العلم',
        description: 'Publier 100 articles',
        icon: Icons.article,
        color: const Color(0xFF607D8B),
        requiredHassanat: 2000,
        category: 'Savoir',
      ),
      SpiritualBadge(
        id: 'peace_maker',
        name: 'Pacificateur',
        arabicName: 'صانع السلام',
        description: 'Réconcilier 50 personnes',
        icon: Icons.handshake_outlined,
        color: const Color(0xFF4CAF50),
        requiredHassanat: 1250,
        category: 'Paix',
      ),
      SpiritualBadge(
        id: 'sick_visitor',
        name: 'Visiteur Malades',
        arabicName: 'عائد المرضى',
        description: 'Visiter 100 malades',
        icon: Icons.local_hospital,
        color: const Color(0xFFE57373),
        requiredHassanat: 1000,
        category: 'Santé',
      ),
      SpiritualBadge(
        id: 'allah_beloved',
        name: 'Bien-Aimé Allah',
        arabicName: 'حبيب الله',
        description: 'Atteindre 5000 hassanat',
        icon: Icons.stars_outlined,
        color: const Color(0xFFFFD700),
        requiredHassanat: 5000,
        category: 'Excellence',
      ),
      SpiritualBadge(
        id: 'ultimate_believer',
        name: 'Croyant Ultime',
        arabicName: 'المؤمن الأسمى',
        description: 'Atteindre 10000 hassanat',
        icon: Icons.military_tech,
        color: const Color(0xFFE65100),
        requiredHassanat: 10000,
        category: 'Excellence',
      ),
      SpiritualBadge(
        id: 'eternal_servant',
        name: 'Serviteur Éternel',
        arabicName: 'العبد الأبدي',
        description: 'Atteindre 25000 hassanat',
        icon: Icons.all_inclusive,
        color: const Color(0xFF1A237E),
        requiredHassanat: 25000,
        category: 'Excellence',
      ),
      SpiritualBadge(
        id: 'divine_chosen',
        name: 'Élu Divin',
        arabicName: 'المختار الإلهي',
        description: 'Atteindre 50000 hassanat',
        icon: Icons.auto_awesome_outlined,
        color: const Color(0xFF4A148C),
        requiredHassanat: 50000,
        category: 'Excellence',
      ),

      // Badges spéciaux et saisonniers (101-120)
      SpiritualBadge(
        id: 'new_muslim',
        name: 'Nouveau Musulman',
        arabicName: 'المسلم الجديد',
        description: 'Se convertir à l\'Islam',
        icon: Icons.celebration_outlined,
        color: const Color(0xFF8BC34A),
        requiredHassanat: 1000,
        category: 'Conversion',
      ),
      SpiritualBadge(
        id: 'friday_faithful',
        name: 'Fidèle du Vendredi',
        arabicName: 'مؤمن الجمعة',
        description: 'Assister Jumu\'ah 20 fois',
        icon: Icons.calendar_month,
        color: const Color(0xFF1976D2),
        requiredHassanat: 300,
        category: 'Vendredi',
      ),
      SpiritualBadge(
        id: 'laylat_qadr',
        name: 'Nuit du Destin',
        arabicName: 'ليلة القدر',
        description: 'Prier Laylat al-Qadr',
        icon: Icons.star_purple500_outlined,
        color: const Color(0xFF7B1FA2),
        requiredHassanat: 833,
        category: 'Nuits',
      ),
      SpiritualBadge(
        id: 'eid_celebrant',
        name: 'Célébrant Eid',
        arabicName: 'محتفل العيد',
        description: 'Célébrer 10 Eids',
        icon: Icons.party_mode,
        color: const Color(0xFFFF9800),
        requiredHassanat: 500,
        category: 'Eid',
      ),
      SpiritualBadge(
        id: 'ashura_faster',
        name: 'Jeûneur Ashura',
        arabicName: 'صائم عاشوراء',
        description: 'Jeûner jour d\'Ashura 5 fois',
        icon: Icons.event_note,
        color: const Color(0xFF795548),
        requiredHassanat: 125,
        category: 'Ashura',
      ),
      SpiritualBadge(
        id: 'arafat_prayer',
        name: 'Prieur Arafat',
        arabicName: 'مصلي عرفة',
        description: 'Prier jour d\'Arafat 3 fois',
        icon: Icons.landscape,
        color: const Color(0xFF8D6E63),
        requiredHassanat: 150,
        category: 'Arafat',
      ),
    ];
  }
}