import 'package:flutter/material.dart';

enum ActionType {
  prayer,
  dhikr,
  charity,
  quranReading,
  goodDeed,
  hadith,
  sunnah,
  socialService,
  family,
  worship,
  names99
}

class IslamicAction {
  final String id;
  final String title;
  final String arabicTitle;
  final String description;
  final int hassanatReward;
  final ActionType type;
  final IconData icon;
  final bool isCompleted;
  final DateTime? completionDate;
  final String? detailedDescription;
  final List<String>? hadiths;
  final String? audioUrl;
  final String? islamicTeaching;

  IslamicAction({
    required this.id,
    required this.title,
    required this.arabicTitle,
    required this.description,
    required this.hassanatReward,
    required this.type,
    required this.icon,
    this.isCompleted = false,
    this.completionDate,
    this.detailedDescription,
    this.hadiths,
    this.audioUrl,
    this.islamicTeaching,
  });

  IslamicAction copyWith({
    String? id,
    String? title,
    String? arabicTitle,
    String? description,
    int? hassanatReward,
    ActionType? type,
    IconData? icon,
    bool? isCompleted,
    DateTime? completionDate,
    String? detailedDescription,
    List<String>? hadiths,
    String? audioUrl,
    String? islamicTeaching,
  }) {
    return IslamicAction(
      id: id ?? this.id,
      title: title ?? this.title,
      arabicTitle: arabicTitle ?? this.arabicTitle,
      description: description ?? this.description,
      hassanatReward: hassanatReward ?? this.hassanatReward,
      type: type ?? this.type,
      icon: icon ?? this.icon,
      isCompleted: isCompleted ?? this.isCompleted,
      completionDate: completionDate ?? this.completionDate,
      detailedDescription: detailedDescription ?? this.detailedDescription,
      hadiths: hadiths ?? this.hadiths,
      audioUrl: audioUrl ?? this.audioUrl,
      islamicTeaching: islamicTeaching ?? this.islamicTeaching,
    );
  }

  static List<IslamicAction> getDefaultActions() {
    return [
      IslamicAction(
        id: 'prayer_fajr',
        title: 'Prière du Fajr',
        arabicTitle: 'صلاة الفجر',
        description: 'Accomplir la prière de l\'aube',
        hassanatReward: 10,
        type: ActionType.prayer,
        icon: Icons.wb_sunny_outlined,
      ),
      IslamicAction(
        id: 'prayer_dhuhr',
        title: 'Prière du Dhuhr',
        arabicTitle: 'صلاة الظهر',
        description: 'Accomplir la prière de midi',
        hassanatReward: 10,
        type: ActionType.prayer,
        icon: Icons.wb_sunny,
      ),
      IslamicAction(
        id: 'prayer_asr',
        title: 'Prière du Asr',
        arabicTitle: 'صلاة العصر',
        description: 'Accomplir la prière de l\'après-midi',
        hassanatReward: 10,
        type: ActionType.prayer,
        icon: Icons.wb_cloudy,
      ),
      IslamicAction(
        id: 'prayer_maghrib',
        title: 'Prière du Maghrib',
        arabicTitle: 'صلاة المغرب',
        description: 'Accomplir la prière du coucher du soleil',
        hassanatReward: 10,
        type: ActionType.prayer,
        icon: Icons.brightness_3,
      ),
      IslamicAction(
        id: 'prayer_isha',
        title: 'Prière du Isha',
        arabicTitle: 'صلاة العشاء',
        description: 'Accomplir la prière du soir',
        hassanatReward: 10,
        type: ActionType.prayer,
        icon: Icons.nights_stay,
      ),
      // Nouvelle action: prière à l'heure (suivi global des 5 prières à l'heure)
      IslamicAction(
        id: 'prayer_on_time',
        title: 'Prière à l’heure',
        arabicTitle: 'الصلاة على وقتها',
        description: 'Accomplir chaque prière obligatoire à son heure',
        hassanatReward: 20,
        type: ActionType.prayer,
        icon: Icons.alarm_on,
      ),
      IslamicAction(
        id: 'dhikr_morning',
        title: 'Dhikr du matin',
        arabicTitle: 'أذكار الصباح',
        description: 'Réciter les invocations matinales',
        hassanatReward: 5,
        type: ActionType.dhikr,
        icon: Icons.favorite,
        detailedDescription: 'Les invocations du matin protègent le musulman tout au long de la journée et attirent les bénédictions d\'Allah.',
        hadiths: [
          'Le Prophète ﷺ a dit : "Quiconque dit le matin : أعوذ بكلمات الله التامات من شر ما خلق (Je cherche protection auprès des paroles parfaites d\'Allah contre le mal de ce qu\'Il a créé), rien ne lui nuira ce jour-là." (Muslim)',
          'Abou Hourayra a rapporté que le Prophète ﷺ disait le matin : اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور (Ô Allah, c\'est par Toi que nous entrons dans le matin, par Toi que nous entrons dans la soirée, par Toi que nous vivons, par Toi que nous mourrons et vers Toi est la résurrection)." (Tirmidhi)'
        ],
        islamicTeaching: 'Les dhikr du matin établissent une connexion spirituelle dès le réveil et placent la journée sous la protection divine.',
        audioUrl: 'assets/audio/dhikr_morning.mp3',
      ),
      IslamicAction(
        id: 'dhikr_evening',
        title: 'Dhikr du soir',
        arabicTitle: 'أذكار المساء',
        description: 'Réciter les invocations du soir',
        hassanatReward: 5,
        type: ActionType.dhikr,
        icon: Icons.favorite_outline,
        detailedDescription: 'Les invocations du soir purifient l\'âme des péchés de la journée et assurent une protection nocturne.',
        hadiths: [
          'Le Prophète ﷺ a dit : "Quiconque dit le soir : بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم trois fois, rien ne lui nuira jusqu\'au matin." (Abou Dawoud)',
          'Ibn Umar a rapporté que le Prophète ﷺ n\'a jamais délaissé ces invocations le soir et le matin : اللهم إني أسألك العفو والعافية في الدنيا والآخرة (Ô Allah, je Te demande le pardon et la bonne santé dans ce monde et dans l\'au-delà)." (Ibn Majah)'
        ],
        islamicTeaching: 'Les dhikr du soir permettent au croyant de faire le bilan de sa journée et de se préparer spirituellement pour la nuit.',
        audioUrl: 'assets/audio/dhikr_evening.mp3',
      ),
      IslamicAction(
        id: 'quran_reading',
        title: 'Lecture du Coran',
        arabicTitle: 'قراءة القرآن',
        description: 'Lire une partie du Saint Coran',
        hassanatReward: 20,
        type: ActionType.quranReading,
        icon: Icons.menu_book,
      ),
      IslamicAction(
        id: 'charity',
        title: 'Faire l\'aumône',
        arabicTitle: 'الصدقة',
        description: 'Donner de l\'argent ou aider quelqu\'un',
        hassanatReward: 30,
        type: ActionType.charity,
        icon: Icons.volunteer_activism,
      ),
      IslamicAction(
        id: 'good_deed',
        title: 'Bonne action',
        arabicTitle: 'عمل الخير',
        description: 'Accomplir une bonne action',
        hassanatReward: 15,
        type: ActionType.goodDeed,
        icon: Icons.thumb_up,
      ),
      // Actions Hadith & Sunnah
      IslamicAction(
        id: 'read_hadith',
        title: 'Lire un hadith',
        arabicTitle: 'قراءة حديث',
        description: 'Lire et méditer sur un hadith du Prophète ﷺ',
        hassanatReward: 8,
        type: ActionType.hadith,
        icon: Icons.chrome_reader_mode,
        detailedDescription: 'La lecture des hadiths nous permet de mieux comprendre les enseignements du Prophète ﷺ et d\'appliquer sa Sunnah dans notre vie quotidienne.',
        hadiths: [
          'Le Prophète ﷺ a dit : "Celui qui apprend une science pour l\'enseigner aux gens, Allah lui facilite le chemin vers le Paradis." (Tirmidhi)',
          'Abou Hourayra (qu\'Allah soit satisfait de lui) a dit : "Le Messager d\'Allah ﷺ a dit : Quand l\'homme meurt, ses œuvres s\'arrêtent sauf trois : une aumône continue, une science utile ou un enfant pieux qui prie pour lui." (Muslim)'
        ],
        islamicTeaching: 'Les hadiths sont la seconde source de la législation islamique après le Coran. Ils expliquent et détaillent les enseignements coraniques.',
        audioUrl: 'assets/audio/hadith_recitation.mp3',
      ),
      // Nouvelle action améliorée: Lire Hadith (avec plus de détails)
      IslamicAction(
        id: 'study_hadith_collection',
        title: 'Étudier collection Hadith',
        arabicTitle: 'دراسة مجموعة الأحاديث',
        description: 'Étudier une collection de hadiths (Bukhari, Muslim, etc.)',
        hassanatReward: 25,
        type: ActionType.hadith,
        icon: Icons.library_books,
        detailedDescription: 'L\'étude approfondie des collections de hadiths authentiques comme Sahih Bukhari, Sahih Muslim, et autres permet une compréhension plus profonde de l\'Islam.',
        hadiths: [
          'Ibn Abbas (qu\'Allah soit satisfait de lui) a dit : "Quand vous entendez un hadith du Messager d\'Allah ﷺ qui profite à votre cœur et qui vous plaît, et que vous sentez que c\'est vrai, sachez qu\'Allah vous l\'a dit." (Tirmidhi)',
          'Le Prophète ﷺ a dit : "Que celui qui était présent transmette à celui qui était absent, car il se peut que celui à qui on transmet retienne mieux que celui qui a entendu." (Bukhari)'
        ],
        islamicTeaching: 'Les grandes collections de hadiths ont été compilées par des savants qui ont consacré leur vie à préserver authentiquement les paroles du Prophète ﷺ.',
      ),
      IslamicAction(
        id: 'apply_hadith',
        title: 'Appliquer un hadith',
        arabicTitle: 'تطبيق حديث',
        description: 'Mettre en pratique un enseignement du hadith',
        hassanatReward: 25,
        type: ActionType.hadith,
        icon: Icons.check_circle_outline,
      ),
      IslamicAction(
        id: 'sunnah_miswak',
        title: 'Utiliser le Siwak',
        arabicTitle: 'استعمال السواك',
        description: 'Suivre la Sunnah en utilisant le Siwak',
        hassanatReward: 3,
        type: ActionType.sunnah,
        icon: Icons.brush,
      ),
      IslamicAction(
        id: 'sunnah_duha',
        title: 'Prière Duha',
        arabicTitle: 'صلاة الضحى',
        description: 'Accomplir la prière surérogatoire de Duha',
        hassanatReward: 12,
        type: ActionType.sunnah,
        icon: Icons.wb_sunny_outlined,
      ),
      IslamicAction(
        id: 'sunnah_tahajjud',
        title: 'Prière Tahajjud',
        arabicTitle: 'صلاة التهجد',
        description: 'Se lever la nuit pour prier',
        hassanatReward: 35,
        type: ActionType.sunnah,
        icon: Icons.bedtime,
        detailedDescription: 'La prière de Tahajjud est une prière surérogatoire qui se fait la nuit, après avoir dormi et avant l\'aube. C\'est une des prières les plus méritoires.',
        hadiths: [
          'Le Prophète ﷺ a dit : "La meilleure prière après les prières obligatoires est la prière de la nuit." (Muslim)',
          'Aicha (qu\'Allah soit satisfait d\'elle) a dit : "Le Prophète ﷺ priait onze unités de prière la nuit." (Bukhari)'
        ],
        islamicTeaching: 'Tahajjud signifie littéralement "veiller". Cette prière montre la dévotion sincère du croyant qui sacrifie son sommeil pour adorer Allah.',
      ),
      // Nouvelle action: Prière surérogatoire
      IslamicAction(
        id: 'prayer_sunnah_general',
        title: 'Prière surérogatoire',
        arabicTitle: 'الصلاة النافلة',
        description: 'Accomplir des prières surérogatoires (rawatib, duha, etc.)',
        hassanatReward: 20,
        type: ActionType.worship,
        icon: Icons.auto_awesome,
        detailedDescription: 'Les prières surérogatoires incluent les rawatib (prières d\'accompagnement des prières obligatoires), la prière de Duha, Ishraq, et d\'autres prières recommandées.',
        hadiths: [
          'Le Prophète ﷺ a dit : "Celui qui prie 12 unités de prière surérogatoire en une journée, Allah lui construira une maison au Paradis." (Muslim)',
          'Oum Habiba (qu\'Allah soit satisfait d\'elle) a dit : "J\'ai entendu le Messager d\'Allah ﷺ dire : Quiconque prie douze unités de prière surérogatoire en une journée, Allah lui bâtira une maison au Paradis." (Muslim)'
        ],
        islamicTeaching: 'Les prières surérogatoires renforcent notre lien avec Allah et compensent les manquements dans nos prières obligatoires.',
      ),
      // Services sociaux et communautaires
      IslamicAction(
        id: 'visit_sick',
        title: 'Visiter un malade',
        arabicTitle: 'عيادة المريض',
        description: 'Rendre visite à une personne malade',
        hassanatReward: 40,
        type: ActionType.socialService,
        icon: Icons.local_hospital,
      ),
      IslamicAction(
        id: 'help_neighbor',
        title: 'Aider son voisin',
        arabicTitle: 'مساعدة الجار',
        description: 'Offrir de l\'aide à son voisin',
        hassanatReward: 20,
        type: ActionType.socialService,
        icon: Icons.home_filled,
      ),
      IslamicAction(
        id: 'feed_poor',
        title: 'Nourrir un nécessiteux',
        arabicTitle: 'إطعام المسكين',
        description: 'Donner à manger à une personne dans le besoin',
        hassanatReward: 50,
        type: ActionType.socialService,
        icon: Icons.restaurant,
      ),
      IslamicAction(
        id: 'teach_islam',
        title: 'Enseigner l\'Islam',
        arabicTitle: 'تعليم الإسلام',
        description: 'Partager des connaissances islamiques',
        hassanatReward: 30,
        type: ActionType.socialService,
        icon: Icons.school,
      ),
      // Nouvelle action: Planter des arbres
      IslamicAction(
        id: 'plant_trees',
        title: 'Planter des arbres',
        arabicTitle: 'غرس الأشجار',
        description: 'Planter des arbres ou préserver l\'environnement',
        hassanatReward: 40,
        type: ActionType.socialService,
        icon: Icons.eco,
        detailedDescription: 'Planter des arbres et préserver l\'environnement est une action très méritoire en Islam. Chaque arbre planté continue de donner des récompenses tant qu\'il profite aux créatures.',
        hadiths: [
          'Le Prophète ﷺ a dit : "Quiconque plante un arbre et le soigne avec patience jusqu\'à ce qu\'il grandisse et porte des fruits, aura une récompense pour chaque fruit qui en résulte." (Ahmad)',
          'Anas ibn Malik a rapporté que le Prophète ﷺ a dit : "Si l\'Heure arrive alors que l\'un de vous a une pousse dans la main, qu\'il la plante s\'il le peut." (Bukhari dans Al-Adab Al-Mufrad)'
        ],
        islamicTeaching: 'La protection de l\'environnement est un devoir islamique. Allah nous a confié la Terre en tant que khalifa (intendants) pour en prendre soin.',
      ),
      // Nouvelle action: Réconcilier les gens
      IslamicAction(
        id: 'reconcile_people',
        title: 'Réconcilier les gens',
        arabicTitle: 'الإصلاح بين الناس',
        description: 'Réconcilier des personnes en conflit',
        hassanatReward: 70,
        type: ActionType.socialService,
        icon: Icons.handshake,
        detailedDescription: 'La réconciliation entre les gens est une des meilleures œuvres auprès d\'Allah. Cela apporte la paix et renforce les liens communautaires.',
        hadiths: [
          'Allah dit : "La réconciliation est meilleure" (Coran 4:128)',
          'Le Prophète ﷺ a dit : "Réconcilier les gens est meilleur que beaucoup de prières surérogatoires, d\'aumônes et d\'actes de bien." (Abou Dawoud)',
          'Abou Darda (qu\'Allah soit satisfait de lui) a rapporté que le Prophète ﷺ a dit : "Ne vous informerai-je pas de ce qui est supérieur au degré du jeûne, de la prière et de l\'aumône ? Réconcilier les gens, car la corruption des relations humaines rase (les bonnes œuvres)." (Abou Dawoud)'
        ],
        islamicTeaching: 'La réconciliation nécessite sagesse, patience et justice. Elle rétablit l\'harmonie dans la communauté et plaît énormément à Allah.',
      ),
      // Actions familiales
      IslamicAction(
        id: 'respect_parents',
        title: 'Respecter ses parents',
        arabicTitle: 'بر الوالدين',
        description: 'Faire du bien à ses parents',
        hassanatReward: 45,
        type: ActionType.family,
        icon: Icons.family_restroom,
      ),
      IslamicAction(
        id: 'family_prayer',
        title: 'Prière en famille',
        arabicTitle: 'الصلاة الجماعية',
        description: 'Prier ensemble en famille',
        hassanatReward: 18,
        type: ActionType.family,
        icon: Icons.groups,
      ),
      // Adorations supplémentaires
      IslamicAction(
        id: 'istighfar',
        title: 'Istighfar',
        arabicTitle: 'الاستغفار',
        description: 'Demander pardon à Allah (100 fois)',
        hassanatReward: 10,
        type: ActionType.worship,
        icon: Icons.favorite_border,
      ),
      IslamicAction(
        id: 'salawat',
        title: 'Salawat sur le Prophète',
        arabicTitle: 'الصلاة على النبي',
        description: 'Invoquer les bénédictions sur le Prophète ﷺ',
        hassanatReward: 7,
        type: ActionType.worship,
        icon: Icons.auto_awesome,
      ),
      IslamicAction(
        id: 'dua_fasting',
        title: 'Jeûne surérogatoire',
        arabicTitle: 'الصوم النافلة',
        description: 'Jeûner en dehors du Ramadan',
        hassanatReward: 60,
        type: ActionType.worship,
        icon: Icons.dining,
      ),
      IslamicAction(
        id: 'quran_memorization',
        title: 'Mémoriser le Coran',
        arabicTitle: 'حفظ القرآن',
        description: 'Apprendre des versets du Coran par cœur',
        hassanatReward: 100,
        type: ActionType.quranReading,
        icon: Icons.psychology,
      ),
      IslamicAction(
        id: 'remove_harm',
        title: 'Enlever un obstacle',
        arabicTitle: 'إزالة الأذى',
        description: 'Retirer quelque chose de nuisible du chemin',
        hassanatReward: 15,
        type: ActionType.goodDeed,
        icon: Icons.cleaning_services,
      ),
      IslamicAction(
        id: 'smile_sadaqah',
        title: 'Sourire (Sadaqah)',
        arabicTitle: 'الابتسامة صدقة',
        description: 'Offrir un sourire sincère à autrui',
        hassanatReward: 5,
        type: ActionType.goodDeed,
        icon: Icons.sentiment_satisfied,
      ),
      // Actions avec récompenses spéciales
      IslamicAction(
        id: 'recite_al_ikhlas_10',
        title: 'Réciter 10 fois Al-Ikhlas',
        arabicTitle: 'قراءة الإخلاص ١٠ مرات',
        description: 'Réciter 10 fois la sourate n°112 Al-Ikhlas - Récompense: Un Palais',
        hassanatReward: 200,
        type: ActionType.quranReading,
        icon: Icons.castle,
      ),
      IslamicAction(
        id: 'mosque_construction',
        title: 'Construction mosquée',
        arabicTitle: 'بناء مسجد',
        description: 'Participer à la construction d\'une mosquée - Récompense: Un Bayt (maison)',
        hassanatReward: 1000,
        type: ActionType.charity,
        icon: Icons.foundation,
      ),
      IslamicAction(
        id: 'pray_12_sunnah',
        title: '12 Rakats Sunnah',
        arabicTitle: '١٢ ركعة سنة',
        description: 'Prier 12 unités de prière (rakaats) surérogatoires - Récompense: Un Bayt (maison)',
        hassanatReward: 150,
        type: ActionType.sunnah,
        icon: Icons.home,
      ),
      IslamicAction(
        id: 'fill_prayer_gap',
        title: 'Combler rang de prière',
        arabicTitle: 'سد الفرج في الصف',
        description: 'Combler un espace vide dans un rang lors d\'une prière - Récompense: Un Bayt + Un Degré',
        hassanatReward: 160,
        type: ActionType.prayer,
        icon: Icons.format_align_center,
      ),
      IslamicAction(
        id: 'visit_sick_muslim_reward',
        title: 'Visiter musulman malade',
        arabicTitle: 'عيادة المسلم المريض',
        description: 'Rendre visite à un(e) musulman(e) malade - Récompense: Un Manzil + Un Jardin',
        hassanatReward: 180,
        type: ActionType.socialService,
        icon: Icons.local_florist,
      ),
      IslamicAction(
        id: 'visit_muslim',
        title: 'Visiter un musulman',
        arabicTitle: 'زيارة مسلم',
        description: 'Rendre visite à un(e) musulman(e) - Récompense: Un Manzil (maison)',
        hassanatReward: 120,
        type: ActionType.socialService,
        icon: Icons.people_alt,
      ),
      IslamicAction(
        id: 'go_to_mosque',
        title: 'Aller à la mosquée',
        arabicTitle: 'الذهاب إلى المسجد',
        description: 'Aller à la mosquée - Récompense: Un Manzil (maison)',
        hassanatReward: 100,
        type: ActionType.worship,
        icon: Icons.directions_walk,
      ),
      IslamicAction(
        id: 'return_from_mosque',
        title: 'Revenir de la mosquée',
        arabicTitle: 'العودة من المسجد',
        description: 'Revenir de la mosquée - Récompense: Un Manzil (maison)',
        hassanatReward: 100,
        type: ActionType.worship,
        icon: Icons.home_outlined,
      ),
      // Dhikr avec récompenses d'arbres
      IslamicAction(
        id: 'say_subhanallah',
        title: 'Dire Subhanallah',
        arabicTitle: 'سبحان الله',
        description: 'Dire Subhanallah - Récompense: Un Arbre + Une Parole lourde',
        hassanatReward: 50,
        type: ActionType.dhikr,
        icon: Icons.park,
        detailedDescription: 'Subhanallah signifie "Gloire à Allah" et exprime la perfection absolue d\'Allah, exempt de tout défaut.',
        hadiths: [
          'Le Prophète ﷺ a dit : "Celui qui dit سبحان الله وبحمده (Subhanallahi wa bi hamdih) 100 fois par jour, ses péchés seront effacés même s\'ils étaient comme l\'écume de la mer." (Bukhari)',
          'Jabir a rapporté que le Prophète ﷺ a dit : "Pour celui qui dit سبحان الله العظيم وبحمده (Subhanallahi l-adhim wa bi hamdih), un palmier sera planté pour lui au Paradis." (Tirmidhi)'
        ],
        islamicTeaching: 'Ce dhikr purifie l\'âme et rappelle la transcendance absolue d\'Allah au-dessus de toute imperfection.',
        audioUrl: 'assets/audio/subhanallah.mp3',
      ),
      IslamicAction(
        id: 'say_alhamdulillah',
        title: 'Dire Al-Hamdu lillah',
        arabicTitle: 'الحمد لله',
        description: 'Dire Al-Hamdu lillah - Récompense: Un Arbre + Une Parole lourde',
        hassanatReward: 50,
        type: ActionType.dhikr,
        icon: Icons.eco,
        detailedDescription: 'Al-Hamdu lillah signifie "Toute louange appartient à Allah" et exprime la gratitude envers Allah pour tous Ses bienfaits.',
        hadiths: [
          'Le Prophète ﷺ a dit : "الحمد لله remplit la balance." (Muslim)',
          'Anas a rapporté que le Prophète ﷺ a dit : "Allah est satisfait de Son serviteur qui, lorsqu\'il mange quelque chose, Le loue pour cela, et lorsqu\'il boit quelque chose, Le loue pour cela." (Muslim)'
        ],
        islamicTeaching: 'Ce dhikr développe un état de gratitude constant et reconnaît Allah comme la source de tous les bienfaits.',
        audioUrl: 'assets/audio/alhamdulillah.mp3',
      ),
      IslamicAction(
        id: 'say_allahu_akbar',
        title: 'Dire Allahu Akbar',
        arabicTitle: 'الله أكبر',
        description: 'Dire Allahu Akbar - Récompense: Un Arbre + Une Parole lourde',
        hassanatReward: 50,
        type: ActionType.dhikr,
        icon: Icons.forest,
        detailedDescription: 'Allahu Akbar signifie "Allah est le Plus Grand" et affirme la suprématie absolue d\'Allah sur toute chose.',
        hadiths: [
          'Le Prophète ﷺ a dit : "Renouvelez votre foi." On demanda : "Comment renouvelons-nous notre foi ?" Il dit : "Multipliez les paroles : لا إله إلا الله (La ilaha illa Allah)." (Ahmad)',
          'Abdullah ibn Amr a rapporté que le Prophète ﷺ a dit : "Deux qualités, nul homme musulman ne les acquiert sans entrer au Paradis. Elles sont faciles, mais celui qui les pratique est rare : glorifier Allah 10 fois après chaque prière, Le louer 10 fois et dire Allahu Akbar 10 fois." (Tirmidhi)'
        ],
        islamicTeaching: 'Cette phrase rappelle que Allah surpasse tout en grandeur et en puissance, relativisant nos préoccupations mondaines.',
        audioUrl: 'assets/audio/allahu_akbar.mp3',
      ),
      IslamicAction(
        id: 'say_la_ilaha_illallah',
        title: 'Dire Laa ilaaha illallah',
        arabicTitle: 'لا إله إلا الله',
        description: 'Dire Laa ilaaha illallah - Récompense: Un Arbre + Une Parole lourde',
        hassanatReward: 60,
        type: ActionType.dhikr,
        icon: Icons.nature,
        detailedDescription: 'La ilaha illa Allah est la déclaration de l\'unicité divine, le fondement même de la foi islamique.',
        hadiths: [
          'Le Prophète ﷺ a dit : "لا إله إلا الله est la meilleure des invocations, et الحمد لله est la meilleure des adorations." (Tirmidhi)',
          'Abou Said al-Khudri a rapporté que le Prophète ﷺ a dit : "Moïse a dit : Ô Seigneur, enseigne-moi une invocation par laquelle je T\'invoquerai et Te mentionnerai. Il dit : Ô Moïse, dis لا إله إلا الله. Il dit : Ô Seigneur, tous Tes serviteurs disent cela. Il dit : Ô Moïse, si les sept cieux et ceux qui s\'y trouvent, autre que Moi, et les sept terres étaient dans un plateau d\'une balance et لا إله إلا الله dans l\'autre plateau, لا إله إلا الله l\'emporterait." (Ibn Hibban)'
        ],
        islamicTeaching: 'Cette phrase est le témoignage de foi qui ouvre la porte de l\'Islam et constitue la clé du Paradis.',
        audioUrl: 'assets/audio/la_ilaha_illallah.mp3',
      ),
      IslamicAction(
        id: 'say_subhanallahi_adheem',
        title: 'Subhanallahi l-adhim',
        arabicTitle: 'سبحان الله العظيم وبحمده',
        description: 'Dire Subhanallahi l-adhim wa bi hamdih - Récompense: Un Palmier',
        hassanatReward: 80,
        type: ActionType.dhikr,
        icon: Icons.local_florist,
      ),
      IslamicAction(
        id: 'say_la_hawla',
        title: 'Laa hawla wa la quwwata',
        arabicTitle: 'لا حول ولا قوة إلا بالله',
        description: 'Dire Laa hawla wa la quwwata illa billah - Récompense: Une Plante + Un Trésor',
        hassanatReward: 90,
        type: ActionType.dhikr,
        icon: Icons.diamond,
      ),
      // Actions d'apprentissage et d'adoration
      IslamicAction(
        id: 'study_quran_verse',
        title: 'Étudier un verset',
        arabicTitle: 'دراسة آية',
        description: 'Étudier un verset du Coran - Récompense: Un Degré',
        hassanatReward: 30,
        type: ActionType.quranReading,
        icon: Icons.school_outlined,
      ),
      IslamicAction(
        id: 'prostrate_sajda',
        title: 'Se prosterner',
        arabicTitle: 'السجود',
        description: 'Se prosterner - Récompense: Un degré',
        hassanatReward: 25,
        type: ActionType.worship,
        icon: Icons.keyboard_arrow_down,
      ),
      IslamicAction(
        id: 'salat_ala_nabi',
        title: 'Salat sur le Prophète',
        arabicTitle: 'الصلاة على النبي',
        description: 'Prononcer la prière en faveur du prophète - Récompense: Dix Degrés',
        hassanatReward: 100,
        type: ActionType.worship,
        icon: Icons.star,
      ),
      IslamicAction(
        id: 'salat_janazah',
        title: 'Prière mortuaire',
        arabicTitle: 'صلاة الجنازة',
        description: 'Prier une prière mortuaire (salat janazah) - Récompense: Un Qirat',
        hassanatReward: 300,
        type: ActionType.prayer,
        icon: Icons.spa,
      ),
      IslamicAction(
        id: 'accompany_funeral',
        title: 'Accompagner défunt',
        arabicTitle: 'تشييع الميت',
        description: 'Accompagner le défunt jusqu\'à ce qu\'il soit enterré - Récompense: Un Qirat',
        hassanatReward: 350,
        type: ActionType.socialService,
        icon: Icons.directions_walk_outlined,
      ),
      IslamicAction(
        id: 'subhanallahi_wa_bihamdih',
        title: 'Subhanallahi wa bi hamdih',
        arabicTitle: 'سبحان الله وبحمده سبحان الله العظيم',
        description: 'Dire Subhanallahi wa bi hamdih, subhanallahi l-adhim - Récompense: Parole lourde',
        hassanatReward: 70,
        type: ActionType.dhikr,
        icon: Icons.balance,
      ),
      IslamicAction(
        id: 'learn_99_names',
        title: 'Connaître les 99 noms d\'Allah',
        arabicTitle: 'الأسماء الحسنى',
        description: 'Découvrir et méditer sur les beaux noms d\'Allah et leurs significations',
        hassanatReward: 25,
        type: ActionType.names99,
        icon: Icons.auto_awesome,
      ),
    ];
  }
}