import 'package:flutter/material.dart';

class DhikrItem {
  final String id;
  final String arabicText;
  final String transliteration;
  final String meaning;
  final int repetitions;
  final String benefit;
  final String reward;
  final String audioUrl;
  final IconData icon;
  final Color color;
  final String? imageUrl;
  final String? category;
  final String? source;
  final String? hadithReference;

  DhikrItem({
    required this.id,
    required this.arabicText,
    required this.transliteration,
    required this.meaning,
    this.repetitions = 1,
    required this.benefit,
    required this.reward,
    required this.audioUrl,
    required this.icon,
    required this.color,
    this.imageUrl,
    this.category,
    this.source,
    this.hadithReference,
  });
}

class MorningEveningDhikr {
  static List<DhikrItem> getMorningDhikr() {
    return [
      DhikrItem(
        id: 'ayat_kursi_morning',
        arabicText: 'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ',
        transliteration: '''Allāhu lā ilāha illā huwa al-ḥayyu al-qayyūm, lā ta'khudhuhu sinatun wa lā nawm, lahu mā fī s-samāwāti wa mā fī al-arḍ, man dhā alladhī yashfaʿu ʿindahu illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi shay'in min ʿilmihi illā bimā shā'a, wasiʿa kursiyyuhu as-samāwāti wa al-arḍ, wa lā ya'ūduhu ḥifẓuhumā, wa huwa al-ʿaliyyu al-ʿaẓīm.''',
        meaning: '''Allah – il n'y a point de divinité en dehors de Lui, le Vivant, le Subsistant par Lui-même. Ni somnolence ni sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission ? Il connaît leur passé et leur futur, et ils n'embrassent de Sa science que ce qu'Il veut. Son Kursī (Trône) s'étend sur les cieux et la terre, et leur garde ne Lui pèse point. Il est le Très-Haut, le Très-Grand (Coran 2:255).''',
        repetitions: 1,
        benefit: 'Puissant rempart contre le mal et protection jusqu\'au soir. Renforce la foi et le tawakkul.',
        reward: 'Protection assurée par un ange et grande élévation du rang',
        audioUrl: 'https://example.com/audio/ayat_kursi.mp3',
        icon: Icons.castle,
        color: const Color(0xFF1B5E20),
        category: 'Versets Protecteurs',
        source: 'Coran 2:255',
        hadithReference: 'Rapporté par Al-Boukhari et Muslim',
      ),
      DhikrItem(
        id: 'salawat_morning',
        arabicText: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ',
        transliteration: 'Allāhumma ṣalli ʿalā Muḥammad wa ʿalā āli Muḥammad',
        meaning: 'Ô Allah, prie sur Muhammad et sur la famille de Muhammad',
        repetitions: 10,
        benefit: 'Attire dix miséricordes pour une seule prière sur le Prophète ﷺ et éloigne la négligence du cœur.',
        reward: 'Élévation de degrés et effacement des péchés',
        audioUrl: 'https://example.com/audio/salawat_morning.mp3',
        icon: Icons.favorite_border,
        color: const Color(0xFF3F51B5),
        category: 'Prières sur le Prophète',
        source: 'Hadith rapporté par Abu Darda',
        hadithReference: 'Sunan At-Tirmidhi',
      ),
      DhikrItem(
        id: 'salawat_ibrahimiyya',
        arabicText: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ. اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
        transliteration: '''Allāhumma ṣalli ʿalā Muḥammadin wa ʿalā āli Muḥammadin kamā ṣallayta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd. Allāhumma bārik ʿalā Muḥammadin wa ʿalā āli Muḥammadin kamā bārakta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd.''',
        meaning: 'Ô Allah, prie sur Muhammad et sa famille comme Tu as prié sur Ibrahim et sa famille; Tu es Digne de louanges, Glorieux. Ô Allah, bénis Muhammad et sa famille comme Tu as béni Ibrahim et sa famille; Tu es Digne de louanges, Glorieux.',
        repetitions: 5,
        benefit: 'Prière complète et équilibrée unissant les bénédictions et les louanges, inspirée de la sunna dans les prières rituelles.',
        reward: 'Énorme récompense et élévation du statut aux côtés du Prophète et d\'Ibrahim',
        audioUrl: 'https://example.com/audio/salawat_ibrahimiyya.mp3',
        icon: Icons.sentiment_very_satisfied,
        color: const Color(0xFFE91E63),
        category: 'Prières sur le Prophète',
        source: 'Sahih Al-Boukhari et Muslim',
        hadithReference: 'Récitée dans le tachahoud',
      ),
      DhikrItem(
        id: 'salawat_tanjina',
        arabicText: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ، صَلاَةً تُنْجِيه مِنْ كُلِّ هَوْلٍ وَغَمّ، وَتُرْضِيه يَوْمَ الدّيِن',
        transliteration: 'Allāhumma ṣalli ʿalā Muḥammadin ṣalātan tunjīhi min kulli hawlin wa ghamm, wa turḍīhi yawma ad-dīn',
        meaning: 'Ô Allah, prie sur Muhammad d\'une prière qui le sauve de tout malheur et tristesse, et qui le satisfait au Jour du Jugement.',
        repetitions: 5,
        benefit: 'Procure protection, soulagement et satisfaction complète dans les deux mondes.',
        reward: 'Intercession du Prophète et protection divine',
        audioUrl: 'https://example.com/audio/salawat_tanjina.mp3',
        icon: Icons.shield_sharp,
        color: const Color(0xFF00BCD4),
        category: 'Prières sur le Prophète',
        source: 'Hadith rapporté par Al-Khatib Al-Baghdadi',
        hadithReference: 'Prière pour la protection',
      ),
      DhikrItem(
        id: 'salawat_kamila',
        arabicText: 'اللَّهُمَّ صَلِّ صَلاَةً كَامِلَةً، وَأَنِم نَوْمًا هَانِئًا عَلَى مُحَمَّدٍ الَّذِي لاَ يَقُومُ أَحَدٌ مِقَامَهُ',
        transliteration: '''Allāhumma ṣalli ṣalāatan kāmilatan, wa anim nawman hāni\'an ʿalā Muḥammadin alladhī lā yaqūmu aḥadun miqāmah''',
        meaning: 'Ô Allah, prie d\'une prière complète et accorde un repos agréable à Muhammad, celui auprès duquel personne ne peut prétendre à égalité.',
        repetitions: 3,
        benefit: 'Honore le Prophète par une supplication complète et sincère, renforçant la connexion spirituelle.',
        reward: 'Élévation du Prophète et satisfaction divine',
        audioUrl: 'https://example.com/audio/salawat_kamila.mp3',
        icon: Icons.star_rate,
        color: const Color(0xFFFFD700),
        category: 'Prières sur le Prophète',
        source: 'Hadith rapporté dans At-Tirmidhi',
        hadithReference: 'Prière honoring the Prophet',
      ),
      DhikrItem(
        id: 'takbir_consecration_1',
        arabicText: 'اللَّهُ أَكْبَرُ كَبِيرًا، وَالْحَمْدُ لِلَّهِ كَثِيرًا، وَسُبْحَانَ اللَّهِ بُكْرَةً وَأَصِيلاً',
        transliteration: 'Allāhu akbaru kabīran, wa-l-ḥamdu lillāhi kathīran, wa-subḥāna-llāhi bukratan wa-aṣīlan',
        meaning: 'Allah est infiniment plus grand, louange abondante à Allah, et gloire à Allah matin et soir',
        repetitions: 10,
        benefit: 'Remplit le matin de glorification, louange et grandeur d\'Allah, alignant cœur et actions dès l\'aube.',
        reward: 'Chaque takbir vaut mieux que ce monde et ce qu\'il contient',
        audioUrl: 'https://example.com/audio/takbir_consecration.mp3',
        icon: Icons.wb_sunny_outlined,
        color: const Color(0xFFFFB74D),
        imageUrl: 'https://i.ibb.co/6H8mxWD/takbir-morning-light.jpg',
        category: 'Magnification',
        source: 'Hadith d\'Abu Dharr',
        hadithReference: 'Rapporté par At-Tirmidhi et Ibn Majah',
      ),
      DhikrItem(
        id: 'takbir_consecration_2',
        arabicText: 'اللَّهُ أَكْبَرُ لَا إِلَهَ إِلَّا اللَّهُ، اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ وَلِلَّهِ الْحَمْدُ',
        transliteration: 'Allāhu akbar lā ilāha illā-llāh, Allāhu akbar Allāhu akbar wa-lillāhi-l-ḥamd',
        meaning: 'Allah est plus grand, il n\'y a de divinité qu\'Allah, Allah est plus grand, Allah est plus grand, et à Allah la louange',
        repetitions: 7,
        benefit: 'Purifie l\'âme, renforce le tawḥīd et abreuve le cœur de louanges apaisantes.',
        reward: 'Multiplication des hassanat et effacement des péchés',
        audioUrl: 'https://example.com/audio/takbir_consecration_2.mp3',
        icon: Icons.auto_awesome,
        color: const Color(0xFF81C784),
        imageUrl: 'https://i.ibb.co/L5L6ZpT/takbir-sacred-geometry.jpg',
        category: 'Magnification',
        source: 'Dhikr du matin établi',
        hadithReference: 'Sunnah confirmée',
      ),
      DhikrItem(
        id: 'takbir_consecration_3',
        arabicText: 'اللَّهُ أَكْبَرُ مِنْ كُلِّ شَيْءٍ، وَأَعَزُّ مِنْ كُلِّ شَيْءٍ، وَأَجَلُّ مِنْ كُلِّ شَيْءٍ، وَأَكْرَمُ مِنْ كُلِّ شَيْءٍ',
        transliteration: 'Allāhu akbaru min kulli shayʾ, wa-aʿazzu min kulli shayʾ, wa-ajallu min kulli shayʾ, wa-akramu min kulli shayʾ',
        meaning: 'Allah est plus grand que toute chose, plus puissant que toute chose, plus majestueux que toute chose, et plus généreux que toute chose',
        repetitions: 3,
        benefit: 'Affirme la majesté absolue d\'Allah et élève l\'âme au-dessus des préoccupations terrestres.',
        reward: 'Proximité divine et bénédictions multipliées',
        audioUrl: 'https://example.com/audio/takbir_consecration_3.mp3',
        icon: Icons.star_border_rounded,
        color: const Color(0xFF9C27B0),
        imageUrl: 'https://i.ibb.co/w0Qg4JY/takbir-divine-names.jpg',
        category: 'Magnification',
        source: 'Invocation du Prophète ﷺ',
        hadithReference: 'Transmise via la chaîne des savants',
      ),
      DhikrItem(
        id: 'morning_gratitude',
        arabicText: '''أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ. رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ.''',
        transliteration: '''Aṣbaḥnā wa-aṣbaḥa al-mulku lillāh, wa-l-ḥamdu lillāh. Lā ilāha illā Allāhu waḥdahu lā sharīka lah, lahu al-mulku wa lahu al-ḥamd, wa huwa ʿalā kulli shay'in qadīr. Rabbī as'aluka khayra mā fī hādhā al-yawm wa khayra mā baʿdah, wa aʿūdhu bika min sharri mā fī hādhā al-yawm wa sharri mā baʿdah. Rabbī aʿūdhu bika mina al-kasal wa sūʾi al-kibar, rabbī aʿūdhu bika min ʿadhābin fī an-nār wa ʿadhābin fī al-qabr.''',
        meaning: '''Nous voilà au matin et la royauté appartient à Allah; louange à Allah. Nulle divinité si ce n'est Allah, Seul sans associé; à Lui la royauté et à Lui la louange; Il est capable de toute chose. Ô mon Seigneur, je Te demande le bien de ce jour et le bien de ce qui vient après, et je cherche refuge auprès de Toi contre le mal de ce jour et le mal de ce qui vient après. Ô mon Seigneur, je cherche refuge auprès de Toi contre la paresse et la mauvaise fin de la vieillesse. Ô mon Seigneur, je cherche refuge auprès de Toi contre le châtiment du Feu et le châtiment de la tombe.''',
        repetitions: 1,
        benefit: 'Installe la gratitude et la conscience de la Seigneurie d\'Allah en début de journée.',
        reward: 'Sérénité et protection divine toute la journée',
        audioUrl: 'https://example.com/audio/morning_gratitude.mp3',
        icon: Icons.wb_sunny,
        color: const Color(0xFFFFEB3B),
        category: 'Remerciement Matinal',
        source: 'Sunna confirmée',
        hadithReference: 'Rapporté par Muslim',
      ),
      // Additions
      DhikrItem(
        id: 'sayyid_istighfar_morning',
        arabicText: 'اللّهُمَّ أَنْتَ رَبِّي، لا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
        transliteration: '''Allāhumma anta rabbī, lā ilāha illā anta, khalaqtanī wa-anā ʿabduka, wa-anā ʿalā ʿahdika wa-waʿdika mā istaṭaʿtu, aʿūdhu bika min sharri mā ṣanaʿtu, abū'u laka bi niʿmatika ʿalayya, wa abū'u bi dhanbī, faghfir lī, fa innahu lā yaghfiru adh-dhunūba illā anta.''',
        meaning: 'Maître de l\'imploration du pardon. Reconnaissance, repentance et demande de pardon complète',
        repetitions: 1,
        benefit: 'Le meilleur istighfar: scelle l\'engagement, reconnaît les bienfaits et implore un pardon complet et sincère.',
        reward: 'Promesse du Paradis pour celui qui le dit sincèrement',
        audioUrl: 'https://example.com/audio/sayyidul_istighfar.mp3',
        icon: Icons.healing,
        color: const Color(0xFF009688),
        category: 'Repentance',
        source: 'Hadith rapporté par At-Tirmidhi',
        hadithReference: 'Le meilleur istighfar - Sunan At-Tirmidhi',
      ),
      DhikrItem(
        id: 'bismillah_protection_morning',
        arabicText: 'بِسْمِ اللَّهِ الَّذِي لا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
        transliteration: 'Bismi-llāhi alladhī lā yaḍurru maʿa-smihi shayʾun fī-l-arḍi wa-lā fī-s-samāʾi wa huwa-s-samīʿu-l-ʿalīm',
        meaning: 'Au nom d\'Allah, avec le Nom duquel rien ne peut nuire sur terre ni au ciel; Il est l\'Audient, l\'Omniscient',
        repetitions: 3,
        benefit: 'Bouclier contre les nuisances visibles et invisibles tout au long de la journée.',
        reward: 'Aucun mal ne l\'atteindra ce jour-là par la volonté d\'Allah',
        audioUrl: 'https://example.com/audio/bismillah_protection.mp3',
        icon: Icons.shield_moon,
        color: const Color(0xFF00796B),
      ),
      DhikrItem(
        id: 'subhan_bihamdihi_100_morning',
        arabicText: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
        transliteration: 'Subḥānallāhi wa bi-ḥamdih',
        meaning: 'Gloire et louange à Allah',
        repetitions: 100,
        benefit: 'Efface les péchés même s\'ils sont comme l\'écume de la mer et illumine le cœur.',
        reward: 'Immenses hassanat et pardon',
        audioUrl: 'https://example.com/audio/subhan_bihamdihi.mp3',
        icon: Icons.waterfall_chart,
        color: const Color(0xFF4CAF50),
      ),
      DhikrItem(
        id: 'la_ilaha_wahdahu_100_morning',
        arabicText: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
        transliteration: 'Lā ilāha illā Allāhu waḥdahu lā sharīka lah, lahu al-mulku wa lahu al-ḥamd, wa huwa ʿalā kulli shayʾin qadīr',
        meaning: 'Nulle divinité autre qu\'Allah, Seul sans associé. À Lui la royauté et la louange, et Il est capable de toute chose',
        repetitions: 100,
        benefit: 'Équivaut à affranchir dix esclaves, inscrit cent bonnes actions, efface cent mauvaises et protège toute la journée.',
        reward: 'Immense récompense quotidienne',
        audioUrl: 'https://example.com/audio/la_ilaha_wahdahu.mp3',
        icon: Icons.workspace_premium,
        color: const Color(0xFF8BC34A),
      ),
    ];
  }

  static List<DhikrItem> getEveningDhikr() {
    return [
      DhikrItem(
        id: 'ayat_kursi_evening',
        arabicText: 'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ',
        transliteration: '''Allāhu lā ilāha illā huwa al-ḥayyu al-qayyūm, lā ta'khudhuhu sinatun wa lā nawm, lahu mā fī s-samāwāti wa mā fī al-arḍ, man dhā alladhī yashfaʿu ʿindahu illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi shay'in min ʿilmihi illā bimā shā'a, wasiʿa kursiyyuhu as-samāwāti wa al-arḍ, wa lā ya'ūduhu ḥifẓuhumā, wa huwa al-ʿaliyyu al-ʿaẓīm.''',
        meaning: '''Allah – il n'y a point de divinité en dehors de Lui, le Vivant, le Subsistant par Lui-même... Son Kursī s'étend sur les cieux et la terre et leur garde ne Lui pèse point. Il est le Très-Haut, le Très-Grand (Coran 2:255).''',
        repetitions: 1,
        benefit: 'Bouclier nocturne: apaise le cœur, dissipe les maléfices et protège jusqu\'au matin.',
        reward: 'Protection des anges jusqu\'au matin',
        audioUrl: 'https://example.com/audio/ayat_kursi_evening.mp3',
        icon: Icons.castle,
        color: const Color(0xFF1B5E20),
        category: 'Versets Protecteurs',
        source: 'Coran 2:255',
        hadithReference: 'Rapporté par Al-Boukhari et Muslim',
      ),
      DhikrItem(
        id: 'salawat_evening',
        arabicText: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ',
        transliteration: 'Allāhumma ṣalli ʿalā Muḥammad wa ʿalā āli Muḥammad',
        meaning: 'Ô Allah, prie sur Muhammad et sur la famille de Muhammad',
        repetitions: 10,
        benefit: 'Multiplie la miséricorde et le salut sur le Prophète ﷺ en clôture de journée, et illumine la nuit.',
        reward: 'Élévation de degrés et effacement des péchés',
        audioUrl: 'https://example.com/audio/salawat_evening.mp3',
        icon: Icons.favorite,
        color: const Color(0xFFE91E63),
        category: 'Prières sur le Prophète',
        source: 'Hadith rapporté par Abu Darda',
        hadithReference: 'Sunan At-Tirmidhi',
      ),
      DhikrItem(
        id: 'takbir_evening_1',
        arabicText: 'اللَّهُ أَكْبَرُ إِذْ هَدَانَا، وَاللَّهُ أَكْبَرُ إِذْ تَوَلَّانَا، وَاللَّهُ أَكْبَرُ إِذْ كَفَانَا',
        transliteration: 'Allāhu akbar idh hadānā, wa-llāhu akbar idh tawallānā, wa-llāhu akbar idh kafānā',
        meaning: 'Allah est plus grand car Il nous a guidés, nous a pris en charge et nous a suffi',
        repetitions: 7,
        benefit: 'Fait le bilan des faveurs d\'Allah reçues dans la journée et confie la nuit à Sa protection.',
        reward: 'Bilan spirituel positif et protection nocturne',
        audioUrl: 'https://example.com/audio/takbir_evening.mp3',
        icon: Icons.nights_stay_outlined,
        color: const Color(0xFF5C6BC0),
        imageUrl: 'https://i.ibb.co/JzZ8FLq/takbir-evening-stars.jpg',
        category: 'Magnification',
        source: 'Hadith d\'Abu Dharr',
        hadithReference: 'Rapporté par At-Tirmidhi',
      ),
      DhikrItem(
        id: 'takbir_evening_2',
        arabicText: 'اللَّهُ أَكْبَرُ عَدَدَ النُّجُومِ، وَاللَّهُ أَكْبَرُ عَدَدَ الرِّمَالِ وَالأَوْرَاقِ، وَاللَّهُ أَكْبَرُ مِمَّا أَخَافُ وَأَحْذَرُ',
        transliteration: 'Allāhu akbar ʿadada-n-nujūm, wa-llāhu akbar ʿadada-r-rimāli wa-l-awrāq, wa-llāhu akbar mimmā akhāfu wa-aḥdhar',
        meaning: 'Allah est plus grand que le nombre d\'étoiles, des grains de sable et des feuilles; plus grand que ce que je redoute',
        repetitions: 5,
        benefit: 'Apaise les peurs et confie les inquiétudes au Très-Grand, favorisant un sommeil serein.',
        reward: 'Protection divine et sommeil paisible',
        audioUrl: 'https://example.com/audio/takbir_evening_2.mp3',
        icon: Icons.star_outline,
        color: const Color(0xFF7986CB),
        imageUrl: 'https://i.ibb.co/8DFm3NL/takbir-night-sky.jpg',
      ),
      DhikrItem(
        id: 'evening_gratitude',
        arabicText: '''أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ. رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ.''',
        transliteration: '''Amsaynā wa-amsa al-mulku lillāh, wa-l-ḥamdu lillāh. Lā ilāha illā Allāhu waḥdahu lā sharīka lah, lahu al-mulku wa lahu al-ḥamd, wa huwa ʿalā kulli shay'in qadīr. Rabbī as'aluka khayra mā fī hādhihi al-layla wa khayra mā baʿdahā, wa aʿūdhu bika min sharri mā fī hādhihi al-layla wa sharri mā baʿdahā. Rabbī aʿūdhu bika mina al-kasal wa sūʾi al-kibar, rabbī aʿūdhu bika min ʿadhābin fī an-nār wa ʿadhābin fī al-qabr.''',
        meaning: '''Nous voilà au soir et la royauté appartient à Allah; louange à Allah. Nulle divinité si ce n'est Allah, Seul sans associé; à Lui la royauté et à Lui la louange; Il est capable de toute chose. Ô mon Seigneur, je Te demande le bien de cette nuit et le bien de ce qui vient après, et je cherche refuge auprès de Toi contre le mal de cette nuit et le mal de ce qui vient après. Ô mon Seigneur, je cherche refuge auprès de Toi contre la paresse et la mauvaise fin de la vieillesse. Ô mon Seigneur, je cherche refuge auprès de Toi contre le châtiment du Feu et le châtiment de la tombe.''',
        repetitions: 1,
        benefit: 'Clôture la journée sur la gratitude et la reconnaissance du règne d\'Allah, laissant le cœur paisible.',
        reward: 'Bilan positif de la journée auprès d\'Allah',
        audioUrl: 'https://example.com/audio/evening_gratitude.mp3',
        icon: Icons.nights_stay,
        color: const Color(0xFF3F51B5),
        category: 'Remerciement Nocturne',
        source: 'Sunna confirmée',
        hadithReference: 'Rapporté par Muslim',
      ),
      DhikrItem(
        id: 'evening_protection',
        arabicText: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ، اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ',
        transliteration: 'Aʿūdhu billāhi mina-sh-shayṭāni-r-rajīm, Allāhu lā ilāha illā huwa-l-ḥayyu-l-qayyūm',
        meaning: 'Je cherche refuge auprès d\'Allah contre Satan le lapidé. Allah, point de divinité sauf Lui, le Vivant, le Subsistant',
        repetitions: 3,
        benefit: 'Écarte les tentations nocturnes et les mauvais songes en confiant la nuit à Allah.',
        reward: 'Sommeil paisible et protection nocturne',
        audioUrl: 'https://example.com/audio/evening_protection.mp3',
        icon: Icons.shield,
        color: const Color(0xFF673AB7),
      ),
      // Additions
      DhikrItem(
        id: 'sayyid_istighfar_evening',
        arabicText: 'اللّهُمَّ أَنْتَ رَبِّي، لا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
        transliteration: '''Allāhumma anta rabbī, lā ilāha illā anta, khalaqtanī wa-anā ʿabduka, wa-anā ʿalā ʿahdika wa-waʿdika mā istaṭaʿtu, aʿūdhu bika min sharri mā ṣanaʿtu, abū'u laka bi niʿmatika ʿalayya, wa abū'u bi dhanbī, faghfir lī, fa innahu lā yaghfiru adh-dhunūba illā anta.''',
        meaning: 'Maître de l\'imploration du pardon. Reconnaissance, repentance et demande de pardon complète',
        repetitions: 1,
        benefit: 'Pardonne les péchés si récité le soir avec sincérité',
        reward: 'Promesse du Paradis pour celui qui le dit sincèrement',
        audioUrl: 'https://example.com/audio/sayyidul_istighfar.mp3',
        icon: Icons.healing,
        color: const Color(0xFF009688),
        category: 'Repentance',
        source: 'Hadith rapporté par At-Tirmidhi',
        hadithReference: 'Le meilleur istighfar - Sunan At-Tirmidhi',
      ),
      DhikrItem(
        id: 'bismillah_protection_evening',
        arabicText: 'بِسْمِ اللَّهِ الَّذِي لا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
        transliteration: 'Bismi-llāhi alladhī lā yaḍurru maʿa-smihi shayʾun fī-l-arḍi wa-lā fī-s-samāʾi wa huwa-s-samīʿu-l-ʿalīm',
        meaning: 'Au nom d\'Allah, avec le Nom duquel rien ne peut nuire sur terre ni au ciel; Il est l\'Audient, l\'Omniscient',
        repetitions: 3,
        benefit: 'Protection contre les nuisances de la nuit',
        reward: 'Aucun mal ne l\'atteindra cette nuit-là par la volonté d\'Allah',
        audioUrl: 'https://example.com/audio/bismillah_protection.mp3',
        icon: Icons.shield_moon,
        color: const Color(0xFF00796B),
      ),
      DhikrItem(
        id: 'hasbi_allah_7_evening',
        arabicText: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
        transliteration: 'Ḥasbiyallāhu lā ilāha illā huwa ʿalayhi tawakkaltu wa huwa rabbu al-ʿarshi al-ʿaẓīm',
        meaning: 'Allah me suffit. Nulle divinité en dehors de Lui. Je place ma confiance en Lui, Seigneur du Trône immense',
        repetitions: 7,
        benefit: 'Apporte une quiétude profonde et une confiance totale en Allah face aux difficultés.',
        reward: 'Grande récompense et apaisement du cœur',
        audioUrl: 'https://example.com/audio/hasbiyallahu.mp3',
        icon: Icons.security,
        color: const Color(0xFF607D8B),
      ),
      DhikrItem(
        id: 'subhan_bihamdihi_100_evening',
        arabicText: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
        transliteration: 'Subḥānallāhi wa bi-ḥamdih',
        meaning: 'Gloire et louange à Allah',
        repetitions: 100,
        benefit: 'Efface les péchés même s\'ils sont comme l\'écume de la mer et laisse l\'âme apaisée avant le sommeil.',
        reward: 'Immenses hassanat et pardon',
        audioUrl: 'https://example.com/audio/subhan_bihamdihi.mp3',
        icon: Icons.water_drop,
        color: const Color(0xFF4CAF50),
      ),
    ];
  }
}